export const fishingFacts = [
    "Fish have existed on Earth for over 500 million years long before dinosaurs.",
    "There are around 34000 known fish species more than all other vertebrates combined.",
    "Whale sharks are the largest fish at nearly 18 meters long and several tons in weight.",
    "Whale sharks are gentle plankton filter feeders swimming with mouths open.",
    "Greenland sharks can reach ages of over 200 years making them the longest living vertebrates.",
    "Greenland sharks grow only about 0.5-1 cm per year and mature at around 150 years.",
    "Greenland sharks swim slowly at ~0.76 miles per hour.",
    "Hagfish have depicted to exist for over 330 million years and lack vertebrae.",
    "Hagfish produce slime that can expand thousands of times to deter predators.",
    "Hagfish have four hearts and can absorb oxygen through skin and nostrils.",
    "Coelacanths were thought extinct and rediscovered in 1938 after 65 million years.",
    "Coelacanths can grow over six feet long, live up to 60 years, and give live birth.",
    "Cyclothone bristlemouths are the most abundant vertebrate genus on Earth.",
    "Cyclothone are bioluminescent deep sea fish found below 300 meters.",
    "Ocean sunfish are the heaviest bony fish weighing up to 2500 kilograms.",
    "Ocean sunfish bask on the surface to let birds clean their parasites.",
    "Flying fish can glide up to 200 meters above water to escape predators.",
    "Pufferfish inflate and contain tetrodotoxin which is deadly in small doses.",
    "Stonefish are the most venomous fish capable of causing paralysis or death.",
    "Lungfish can breathe air and survive droughts by cocooning in mud.",
    "Lungfish have been recorded living over 65 years.",
    "Seahorses swim upright and male seahorses carry and birth the offspring.",
    "Clownfish form mucus immunity to live among anemone tentacles.",
    "Sailfish are the fastest fish reaching speeds up to 110 kilometers per hour.",
    "Some tuna and sharks are regionally endothermic retaining heat to stay warm.",
    "Catfish possess up to 175000 taste buds over body and barbels.",
    "Fish use lateral line systems to sense vibrations and movements in water.",
    "Goldfish have memory spans of months disproving the three-second myth.",
    "Some fish can change sex for social or reproductive adaptation.",
    'Mudskippers can "walk" on land and breathe through moist skin.',
    "Barracuda have needle-like teeth and powerful bites and are popular game fish.",
    "Salmon migrate thousands of miles upstream back to birth streams to spawn.",
    "Electric eels can generate shocks up to 600 volts to stun prey.",
    "Anglerfish use bioluminescent lures to attract prey in the deep sea.",
    "Parrotfish grind coral and help produce sand that forms beaches.",
    "Oceanic diversity includes roughly equal numbers of freshwater and marine fish.",
    "Fish fossils date from the Cambrian explosion over 500 million years ago.",
    "Catfish belong to many species with bottom-dwelling omnivorous diets.",
    "Carp can survive low oxygen and dig up mud in winter conditions.",
    "Bluefish are aggressive marine predators with sharp teeth for catching prey.",
    "Trout are adaptable fish some migrating between salt and fresh water.",
    "Snapper species feed on crustaceans and mollusks and often around structures.",
    "Snails and crabs in aquariums help control algae and add habitat activity.",
    "Helmet crab species form colonies and compete for shells in social interactions.",
    "Fish scales grow in rings allowing scientists to approximate age.",
    "Fish can suffocate if dissolved oxygen in water is too low.",
    "Only bony fish can swim in coordinated schools guided by members in the center.",
    "Some desert pupfish survive in hot springs above 113°F (45°C).",
    'Anableps "four-eyed fish" can see above and below water simultaneously.',
    'Piranha get their name from the Tupi word meaning "scissors" for sharp teeth.',
    "Cichlids build nests or pits at spawning times and care for their young.",
    "Electric rays can generate lethal shocks to defense or prey capture.",
    "Fish brains are small but many species show learning and problem solving.",
    "Fish lack eyelids so they do not blink.",
    "Seahorses are among the slowest fish moving just inches per minute.",
    "Coelacanths possess lobed fins like early tetrapods.",
    "Fish communicate acoustically using swim bladder or bone vibrations.",
    "Goldfish can regenerate fins and even parts of heart tissue.",
    "Pufferfish are platonic sushi delicacies with regulated specialist preparation.",
    "Flying fish have been documented gliding up to 660 feet or 200 meters.",
    "Fangtooth deep sea fish have human-sized teeth relative to body size.",
    "Gobies are the world's smallest fish at about half an inch long.",
    "Neotropical freshwater fish account for 10 percent of all vertebrate species.",
    "Jellyfish and starfish are not vertebrates and thus not true fish.",
    "Coelacanth flesh is oily and foul tasting so considered inedible.",
    "Fish shell coloration adapts in days or weeks to blend into surroundings.",
    "Some fish regulate buoyancy using swim bladders.",
    "Freshwater fish generally do not drink water to avoid overload.",
    "Saltwater fish drink seawater to compensate osmotically.",
    "Fish tastebuds exist all over body surfaces.",
    "Fish can detect ultraviolet and infrared light in some species.",
    "Fish scales serve as armor protecting from injury and parasites.",
    "Fish produce a mucus layer to fight infection and streamline movement.",
    "Fish fossils provide evidence of evolution over hundreds of millions of years.",
    "Ancient fly-fishing was practiced in 2nd-century Macedon.",
    "Ancient Chinese used cormorants to catch fish in rivers.",
    "Earliest fishing hooks date back about 42000 years made of bone or wood.",
    "Sport fishing lures sometimes span lengths of school buses.",
    "Fish-aggregating devices attract fish but can harm marine ecosystems.",
    "Overfishing threatens many species including essential reef-builders.",
    "NOAA studies menhaden as key filter feeding species for coastal ecosystems.",
    "Fish homing instincts allow salmon to imprint on natal streams.",
    "Fish memory allows avoidance of dangerous predators or locations.",
    "Fish lateral lines assist navigation through murky water.",
    "Fish can regenerate teeth or throat pharyngeal plates in many species.",
    "Some fish develop camouflage resembling coral or sponges for ambush.",
    "Fish clams dock like lumpsuckers using suction on fins to stick to surfaces.",
    "Fish schools mimic larger forms to confuse predators.",
    "Fish can drown in air when gills collapse and dry out.",
    "Fish sleep quietly without REM but maintain alertness.",
    "Fish use gills to extract oxygen and expel carbon dioxide in water.",
    "Fish migrate seasonally to breed spawn or follow food sources.",
    "Fish markets globally support billions in trade and nutritional use.",
    "Thirty million Americans fish recreationally each year.",
    "Fishing rods with reels emerged in 17th century Europe.",
    "Modern fish finders use sonar to locate underwater schools.",
    "Coelacanths were thought extinct for 65 million years until rediscovered alive in 1938.",
    "Coelacanths can grow over six feet long live up to 60 years and give live birth.",
    "Coelacanths have lobed fins a notochord and electrosensory capabilities.",
    "Hagfish are jawless fish with four hearts breathing through skin and nostrils.",
    "Hagfish produce slime that expands thousands of times to block predator gills.",
    "Greenland sharks can grow up to 20 feet and may live over 200 years.",
    "Greenland shark flesh contains toxins unless processed into hakarl.",
    "Some sharks tuna and opah can retain body heat making them quasi warmblooded.",
    "Flying fish are known to glide above water up to 200 meters.",
    "Fish scales grow in rings allowing age estimation similar to tree rings.",
    "Most fish cannot swim backward except eels and some flatfish species.",
    "Fangtooth deep sea fish have teeth so large they cannot fully close jaws.",
    "Betta fish can learn by association display flaring and build bubble nests.",
    "Anglerfish use bioluminescent lures to attract prey in dark ocean depths.",
    "Desert pupfish survive hot springs above 45 degrees Celsius with adaptations.",
    "Arapaima are ancient freshwater giants dating back 23 million years.",
    "Electric eels can generate shocks up to 600 volts to stun prey.",
    "Parrotfish grind coral and help create sand for beaches.",
    "Fish communicate using swim bladder or bone vibration sounds.",
    "Goldfish can regenerate fins and even parts of their heart.",
    "There are more fish species than all amphibians reptiles birds and mammals combined.",
    "Pufferfish inflate and contain tetrodotoxin deadly in small doses.",
    "Stonefish are the most venomous fish able to cause paralysis or death.",
    "Lungfish can breathe air survive drought by encasing in mud cocoon.",
    "Lungfish have been recorded living over 65 years under human care.",
    "Seahorses swim upright and males carry eggs and give birth.",
    "Clownfish live among anemones by developing protective mucus.",
    "Sailfish reach speeds up to 110 kilometers per hour making them fastest fish.",
    "Catfish have up to 175000 taste buds over their bodies and barbels.",
    "Fish use lateral line to sense vibrations movements and navigate murky water.",
    "Goldfish have memory spans of months debunking the three second myth.",
    "Some fish change sex for social hierarchical or reproductive reasons.",
    "Mudskippers walk on land using modified fins breathe through skin.",
    "Barracuda have needle like teeth and powerful bites popular among anglers.",
    "Salmon migrate thousands of miles upstream to spawn returning to birth stream.",
    "Parrotfish poop sand biological sand factories for reefs.",
    "Ocean diversity includes freshwater and marine fish about equally.",
    "Fish fossils date back to Cambrian explosion over 500 million years ago.",
    "Catfish are bottom dwelling omnivores found in freshwater globally.",
    "Carp survive low oxygen winters by digging up mud rich in detritus.",
    "Bluefish are aggressive predators with sharp teeth targeting schools.",
    "Trout can migrate between salt and freshwater during life cycle.",
    "Snappers feed on crustaceans mollusks frequenting reefs and structures.",
    "Gobies are among smallest fish around half an inch long.",
    "Fangtooth teeth size is proportionally largest compared to body.",
    "Walking catfish can traverse land using pectoral fins survive 18 hours out of water.",
    "Piranha name means scissors in Tupi reflecting sharp teeth.",
    "Cichlids build nests pits for spawning and care for their young.",
    "Electric rays can generate lethal shocks for defense or hunting.",
    "Fish lack eyelids so they do not blink underwater.",
    "Seahorses swim just inches per minute making them slowest fish.",
    "Coelacanth lobed fins resemble early tetrapod limbs.",
    "Fish schools mimic larger shapes to evade predators.",
    "Fish can drown if gills collapse and dry out in air.",
    "Fish sleep without REM stay alert to threats.",
    "Fish use gills to extract oxygen expel carbon dioxide.",
    "Fish migrate seasonally to feed breed or find warmth.",
    "Fishing supports billions globally in trade nutrition and livelihoods.",
    "Over 30 million Americans fish annually spending billions on gear and trips.",
    "Fishing reels first appeared in 17th century Europe.",
    "Fish finders use sonar introduced in 1980s to locate schools.",
    "Noodling involves catching catfish by hand from holes underwater.",
    "Record noodled catfish from Oklahoma weighed 87 pounds.",
    "Otter fishing uses trained otters to herd fish into nets still used in Bangladesh.",
    "Otter fishing dates to Tang dynasty China and 6th century Europe.",
    "Fish aggregating devices mimic debris to attract fish but harm wildlife.",
    "FADs can entangle turtles birds damage reefs wash ashore globally.",
    "Fish photosensitive to ultraviolet infrared light in species like goldfish.",
    "Some fish detect electric fields to sense prey and navigate.",
    "Fish taste buds cover body allowing tasting via skin.",
    "Fish possess muscular swim bladder for buoyancy control.",
    "Freshwater fish rarely drink thanks to osmoregulation.",
    "Saltwater fish drink seawater to balance internal salt levels.",
    "Fish skin mucus layers protect from infection and reduce drag.",
    "Fish scales armor protect against injury parasites disease.",
    "Fish reproduce via eggs live birth or mouthbrooding like seahorses.",
    "Fish pharyngeal teeth grind food in throat when stomach absent.",
    "Fish shoot forward jaws in snap feeding attacks.",
    "Stone age fishhooks crafted from bone stone wood thousands of years ago.",
    "Ancient Chinese used trained cormorants as living fishing tools.",
    "Ancient fly fishing dates back to 2nd century Macedon.",
    "Bluefin tuna is most expensive fish sold by weight.",
    "Sailfish black marlin swordfish called speed demons of sea.",
    "Deep sea fishing brings up bizarre creatures like anglerfish hatchetfish.",
    "Menhaden are key coastal filter feeders studied by NOAA.",
    "Fish schooling reduces individual predator threats via confusion.",
    "Fish camouflage can adapt in days to match environment.",
    "Fish fossil study tracks evolutionary adaptation over millions of years.",
    "Betta fish build bubble nests exhibit territorial aggression.",
    "Betta fish learn by associative conditioning respond to cues.",
    "Fastest fish sailfish can swim at speed similar to cheetahs over land.",
    "Fish auditory communication includes grunts clicks croaks via swim bladder.",
    "Fish lateral line helps detect prey navigate currents avoid collisions.",
    "Fish bite size varies from microscopic plankton eaters to giant sharks.",
    "Fish mouthparts vary chew grind or swallow based on feeding style.",
    "Mermaid legend roots from manatees dug from fish sightings.",
    "Fish lantern species glow to attract mates prey defense.",
    "Fish deep sea angler use blinking lure appendage to bait prey.",
    "Fish red tide toxins accumulate in food chain harm humans.",
    "Fish shark awareness programs highlight shark depredation on caught fish.",
    "Channel catfish record in WV was 46.7 lb caught with childs pink rod.",
    "Fish have been on Earth for over 500 million years, predating dinosaurs.",
    "Jellyfish and starfish are not true fish because they lack backbones.",
    "Fish have a specialized lateral line system to detect vibrations in water.",
    "Some fish, like the parrotfish, can change sex during their lifetime.",
    "Fish can drown if their gills collapse and dry out in air.",
    "Fish scales grow in rings, allowing scientists to determine their age.",
    "Flying fish can glide above water up to 200 meters and six meters high.",
    "Fish communicate using swim bladder or bone vibrations.",
    "Goldfish can regenerate fins and parts of their heart tissue over time.",
    "Some fish can learn by association and display flaring behavior.",
    "Some fish can communicate acoustically using swim bladder or bone vibrations.",
    "Anglerfish can swallow prey twice their body size due to expandable jaws.",
    "Most fish cannot swim backward except for eels and some flatfish.",
    "Fangtooth deep-sea fish have teeth so large they cannot fully close their jaws.",
    "Siamese fighting fish, also known as bettas, can learn by association and display flaring behavior.",
    "Siamese fighting fish are territorial and build bubble nests in captivity.",
    "Anglerfish use bioluminescent lures to attract prey in the deep ocean.",
    "Fish have been on Earth for over 500 million years, predating dinosaurs.",
    "Jellyfish and starfish are not true fish because they lack backbones.",
    "Fish have a specialized lateral line system to detect vibrations in water.",
    "Some fish, like the parrotfish, can change sex during their lifetime.",
    "Fish can drown if their gills collapse and dry out in air.",
    "Flying fish can glide above water up to 200 meters and six meters high.",
    "Fish communicate using swim bladder or bone vibrations.",
    "Arapaima is an ancient freshwater fish dating back 23 million years and among the largest scaled fish.",
    "Some freshwater desert pupfish survive in hot springs over 45°C by special adaptations.",
];
