import { CatchDetails, RARITY_POINTS } from "./constants"; // Import from constants
import { pickRandom } from "@/utils/misc";

export const fishTable: CatchDetails[] = [
    // Legendary fish - massive sizes
    { sellValue: RARITY_POINTS.Legendary, name: "Golden Fish", rarity: "Legendary", size: 500, weight: 1000 },
    { sellValue: RARITY_POINTS.Legendary, name: "Ancient Whale", rarity: "Legendary", size: 3000, weight: 150000 },
    { sellValue: RARITY_POINTS.Legendary, name: "Kraken", rarity: "Legendary", size: 5000, weight: 200000 },
    { sellValue: RARITY_POINTS.Legendary, name: "Leviathan", rarity: "Legendary", size: 10000, weight: 500000 },
    { sellValue: RARITY_POINTS.Legendary, name: "Megalodon", rarity: "Legendary", size: 1800, weight: 70000 },
    { sellValue: RARITY_POINTS.Legendary, name: "Helicoprion", rarity: "Legendary", size: 800, weight: 500 },
    { sellValue: RARITY_POINTS.Legendary, name: "Leedsichthys", rarity: "Legendary", size: 1200, weight: 15000 },

    {
        sellValue: RARITY_POINTS.Legendary * 5,
        name: "Mushy",
        emote: () => pickRandom(["mushyJam", "mushyOk", "mushySit", "mushyWheel"]),
        rarity: "Legendary",
        size: 40,
        weight: 4,
    },
    {
        sellValue: RARITY_POINTS.Legendary * 5,
        name: "Socko",
        emote: () => pickRandom(["shocko", "wideSock", "sockTime", "sockZZZ", "sockBday", "sockSludge", "fusSock"]),
        rarity: "Legendary",
        size: 30,
        weight: 4,
    },
    {
        sellValue: RARITY_POINTS.Legendary * 10,
        name: "April Fooze",
        emote: () => pickRandom(["fusApril", "fusMoney", "fusVlog"]),
        rarity: "Legendary",
        size: 170,
        weight: 60,
    },
    {
        sellValue: RARITY_POINTS.Legendary * 15,
        name: "Fuslie",
        emote: () => pickRandom(["fus7", "fusW", "fusBald", "fusFarm", "fusLurks", "fusUnprepared", "periodt", "WOWMOM", "fusJR"]),
        rarity: "Legendary",
        size: 170,
        weight: 60,
    },

    // Epic fish - very large sizes
    { sellValue: RARITY_POINTS.Epic, name: "Giant Tuna", rarity: "Epic", size: 300, weight: 500 },
    { sellValue: RARITY_POINTS.Epic, name: "Colossal Squid", rarity: "Epic", size: 1000, weight: 500 },
    { sellValue: RARITY_POINTS.Epic, name: "Giant Oarfish", rarity: "Epic", size: 800, weight: 270 },
    { sellValue: RARITY_POINTS.Epic, name: "Sunfish", rarity: "Epic", size: 400, weight: 2200 },
    { sellValue: RARITY_POINTS.Epic, name: "Blue Whale", rarity: "Epic", size: 2500, weight: 130000 },
    { sellValue: RARITY_POINTS.Epic, name: "Alligator", rarity: "Epic", size: 400, weight: 250 },
    { sellValue: RARITY_POINTS.Epic, name: "Manta Ray", rarity: "Epic", size: 350, weight: 600 },
    { sellValue: RARITY_POINTS.Epic, name: "Coelacanth", rarity: "Epic", size: 150, weight: 100 },
    { sellValue: RARITY_POINTS.Epic, name: "Man O' War", rarity: "Epic", size: 30, weight: 10 },
    { sellValue: RARITY_POINTS.Epic, name: "Ghost Fish", rarity: "Epic", size: 10, weight: 0.45 },
    { sellValue: RARITY_POINTS.Epic, name: "Stonefish", rarity: "Epic", size: 40, weight: 2.5 },
    { sellValue: RARITY_POINTS.Epic, name: "Anglerfish ", rarity: "Epic", size: 100, weight: 20 },
    { sellValue: RARITY_POINTS.Epic, name: "Napoleon Wrasse", rarity: "Epic", size: 250, weight: 150 },
    { sellValue: RARITY_POINTS.Epic, name: "Lion's Mane Jellyfish", rarity: "Epic", size: 200, weight: 100 },
    { sellValue: RARITY_POINTS.Epic, name: "Dorado", rarity: "Epic", size: 140, weight: 20 },

    // Rare fish - large sizes
    { sellValue: RARITY_POINTS.Rare, name: "Swordfish", rarity: "Rare", size: 350, weight: 540 },
    { sellValue: RARITY_POINTS.Rare, name: "Great White Shark", rarity: "Rare", size: 600, weight: 2000 },
    { sellValue: RARITY_POINTS.Rare, name: "Hammerhead Shark", rarity: "Rare", size: 400, weight: 450 },
    { sellValue: RARITY_POINTS.Rare, name: "Giant Octopus", rarity: "Rare", size: 450, weight: 250 },
    { sellValue: RARITY_POINTS.Rare, name: "Moray Eel", rarity: "Rare", size: 300, weight: 30 },
    { sellValue: RARITY_POINTS.Rare, name: "Lobster", rarity: "Rare", size: 50, weight: 2 },
    { sellValue: RARITY_POINTS.Rare, name: "Axolotl", rarity: "Rare", size: 60, weight: 3 },
    { sellValue: RARITY_POINTS.Rare, name: "Seahorse", rarity: "Rare", size: 15, weight: 0.1 },
    { sellValue: RARITY_POINTS.Rare, name: "Oyster", rarity: "Rare", size: 20, weight: 0.2 },
    { sellValue: RARITY_POINTS.Rare, name: "Sting Ray", rarity: "Rare", size: 150, weight: 50 },
    { sellValue: RARITY_POINTS.Rare, name: "Wolffish", rarity: "Rare", size: 150, weight: 20 },
    { sellValue: RARITY_POINTS.Rare, name: "Sawfish", rarity: "Rare", size: 400, weight: 350 },
    { sellValue: RARITY_POINTS.Rare, name: "Pufferfish", rarity: "Rare", size: 50, weight: 2.5 },
    { sellValue: RARITY_POINTS.Rare, name: "Lingcod", rarity: "Rare", size: 120, weight: 14 },
    { sellValue: RARITY_POINTS.Rare, name: "Orca", rarity: "Rare", size: 600, weight: 300 },
    { sellValue: RARITY_POINTS.Rare, name: "Penguin", rarity: "Rare", size: 100, weight: 20 },
    { sellValue: RARITY_POINTS.Rare, name: "Arowana", rarity: "Rare", size: 100, weight: 30 },
    { sellValue: RARITY_POINTS.Rare, name: "Arapaima", rarity: "Rare", size: 300, weight: 200 },

    // Fine fish - above average sizes
    { sellValue: RARITY_POINTS.Fine, name: "King Salmon", rarity: "Fine", size: 150, weight: 45 },
    { sellValue: RARITY_POINTS.Fine, name: "Giant Grouper", rarity: "Fine", size: 270, weight: 400 },
    { sellValue: RARITY_POINTS.Fine, name: "Halibut", rarity: "Fine", size: 200, weight: 220 },
    { sellValue: RARITY_POINTS.Fine, name: "Electric Ray", rarity: "Fine", size: 180, weight: 90 },
    { sellValue: RARITY_POINTS.Fine, name: "Walleye", rarity: "Fine", size: 65, weight: 2.5 },
    { sellValue: RARITY_POINTS.Fine, name: "Sea Turtle", rarity: "Fine", size: 180, weight: 400 },
    { sellValue: RARITY_POINTS.Fine, name: "Pupfish", rarity: "Fine", size: 5, weight: 0.1 },
    { sellValue: RARITY_POINTS.Fine, name: "Horseshoe Crab", rarity: "Fine", size: 50, weight: 2 },
    { sellValue: RARITY_POINTS.Fine, name: "Shrimp", rarity: "Fine", size: 10, weight: 0.1 },
    { sellValue: RARITY_POINTS.Fine, name: "Lionfish", rarity: "Fine", size: 38, weight: 0.6 },
    { sellValue: RARITY_POINTS.Fine, name: "Dusky Flathead", rarity: "Fine", size: 70, weight: 5 },
    { sellValue: RARITY_POINTS.Fine, name: "Gar", rarity: "Fine", size: 200, weight: 90 },
    { sellValue: RARITY_POINTS.Fine, name: "Guppy", rarity: "Fine", size: 5, weight: 0.05 },
    { sellValue: RARITY_POINTS.Fine, name: "Starfish", rarity: "Fine", size: 20, weight: 3 },
    { sellValue: RARITY_POINTS.Fine, name: "Sea Cucumber", rarity: "Fine", size: 30, weight: 2.3 },
    { sellValue: RARITY_POINTS.Fine, name: "Albacore", rarity: "Fine", size: 120, weight: 15 },
    { sellValue: RARITY_POINTS.Fine, name: "Shad", rarity: "Fine", size: 60, weight: 4 },
    { sellValue: RARITY_POINTS.Fine, name: "Butterfly Fish", rarity: "Fine", size: 20, weight: 0.5 },
    { sellValue: RARITY_POINTS.Fine, name: "Dab", rarity: "Fine", size: 30, weight: 1 },
    { sellValue: RARITY_POINTS.Fine, name: "Frog", rarity: "Fine", size: 10, weight: 0.2, emote: () => pickRandom(["FROG", "Pog"]) },
    { sellValue: RARITY_POINTS.Fine, name: "Sea Urchin", rarity: "Fine", size: 15, weight: 0.3 },
    { sellValue: RARITY_POINTS.Fine, name: "Dolphin", rarity: "Fine", size: 250, weight: 200 },
    { sellValue: RARITY_POINTS.Fine, name: "Triggerfish", rarity: "Fine", size: 50, weight: 3 },
    { sellValue: RARITY_POINTS.Fine, name: "Snapping Turtle", rarity: "Fine", size: 50, weight: 150 },
    { sellValue: RARITY_POINTS.Fine, name: "Barred Knifejaw", rarity: "Fine", size: 80, weight: 7 },

    // Uncommon fish - medium sizes
    { sellValue: RARITY_POINTS.Uncommon, name: "Blue Marlin", rarity: "Uncommon", size: 280, weight: 170 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Striped Bass", rarity: "Uncommon", size: 120, weight: 35 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Yellowfin Tuna", rarity: "Uncommon", size: 200, weight: 180 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Red Snapper", rarity: "Uncommon", size: 90, weight: 22 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Mahi Mahi", rarity: "Uncommon", size: 150, weight: 40 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Rainbow Trout", rarity: "Uncommon", size: 80, weight: 12 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Barracuda", rarity: "Uncommon", size: 180, weight: 45 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Clownfish", rarity: "Uncommon", size: 20, weight: 0.2 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Bowfin", rarity: "Uncommon", size: 50, weight: 3 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Atlantic Salmon", rarity: "Uncommon", size: 80, weight: 8 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Crayfish", rarity: "Uncommon", size: 15, weight: 0.15 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Perch", rarity: "Uncommon", size: 20, weight: 0.5 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Drum", rarity: "Uncommon", size: 60, weight: 6 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Muskellunge", rarity: "Uncommon", size: 115, weight: 13 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Blobfish", rarity: "Uncommon", size: 40, weight: 2, emote: () => "FishMoley" },
    { sellValue: RARITY_POINTS.Uncommon, name: "Red Mullet", rarity: "Uncommon", size: 30, weight: 0.7 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Tilapia", rarity: "Uncommon", size: 60, weight: 3 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Piranha", rarity: "Uncommon", size: 25, weight: 0.5 },
    { sellValue: RARITY_POINTS.Uncommon, name: "Surgeonfish", rarity: "Uncommon", size: 35, weight: 6, emote: () => "fusDory" },
    { sellValue: RARITY_POINTS.Uncommon, name: "Sea Horse", rarity: "Uncommon", size: 20, weight: 0.5 },

    // Common fish - small sizes
    { sellValue: RARITY_POINTS.Common, name: "Snail", rarity: "Common", size: 4, weight: 0.2 },
    { sellValue: RARITY_POINTS.Common, name: "Crab", rarity: "Common", size: 20, weight: 0.65, emote: () => "YEECLAW" },
    { sellValue: RARITY_POINTS.Common, name: "Tadpole", rarity: "Common", size: 5, weight: 0.01 },
    { sellValue: RARITY_POINTS.Common, name: "Goldfish", rarity: "Common", size: 10, weight: 0.1 },
    { sellValue: RARITY_POINTS.Common, name: "Pond Smelt", rarity: "Common", size: 8, weight: 0.05 },
    { sellValue: RARITY_POINTS.Common, name: "Bitterling", rarity: "Common", size: 6, weight: 0.02 },
    { sellValue: RARITY_POINTS.Common, name: "Cherry Salmon", rarity: "Common", size: 15, weight: 0.3 },
    { sellValue: RARITY_POINTS.Common, name: "Silver Mackerel", rarity: "Common", size: 40, weight: 1.5 },
    { sellValue: RARITY_POINTS.Common, name: "Pike", rarity: "Common", size: 55, weight: 1.2 },
    { sellValue: RARITY_POINTS.Common, name: "Koi Fish", rarity: "Common", size: 20, weight: 0.5 },
    { sellValue: RARITY_POINTS.Common, name: "Sardine", rarity: "Common", size: 15, weight: 0.3 },
    { sellValue: RARITY_POINTS.Common, name: "Herring", rarity: "Common", size: 25, weight: 0.7 },
    { sellValue: RARITY_POINTS.Common, name: "Anchovy", rarity: "Common", size: 12, weight: 0.2 },
    { sellValue: RARITY_POINTS.Common, name: "Sea Bass", rarity: "Common", size: 60, weight: 3 },
    { sellValue: RARITY_POINTS.Common, name: "Cod", rarity: "Common", size: 100, weight: 12 },
    { sellValue: RARITY_POINTS.Common, name: "Flounder", rarity: "Common", size: 45, weight: 2 },
    { sellValue: RARITY_POINTS.Common, name: "Catfish", rarity: "Common", size: 70, weight: 4 },
    { sellValue: RARITY_POINTS.Common, name: "Bullhead", rarity: "Common", size: 35, weight: 1 },
    { sellValue: RARITY_POINTS.Common, name: "Bluefish", rarity: "Common", size: 60, weight: 5 },
    { sellValue: RARITY_POINTS.Common, name: "Carp", rarity: "Common", size: 60, weight: 10 },
    { sellValue: RARITY_POINTS.Common, name: "Sturgeon", rarity: "Common", size: 160, weight: 35 },
    { sellValue: RARITY_POINTS.Common, name: "Angelfish", rarity: "Common", size: 15, weight: 0.05 },
    { sellValue: RARITY_POINTS.Common, name: "Bream", rarity: "Common", size: 50, weight: 3.2 },
    { sellValue: RARITY_POINTS.Common, name: "Chub", rarity: "Common", size: 40, weight: 2.7 },
    { sellValue: RARITY_POINTS.Common, name: "Clam", rarity: "Common", size: 10, weight: 0.2 },
    { sellValue: RARITY_POINTS.Common, name: "Sweetfish", rarity: "Common", size: 70, weight: 4 },
    { sellValue: RARITY_POINTS.Common, name: "Rainbowfish", rarity: "Common", size: 20, weight: 0.2 },
    { sellValue: RARITY_POINTS.Common, name: "Loach", rarity: "Common", size: 50, weight: 3 },
    { sellValue: RARITY_POINTS.Common, name: "Killifish", rarity: "Common", size: 5, weight: 0.05 },
    { sellValue: RARITY_POINTS.Common, name: "Dace", rarity: "Common", size: 15, weight: 0.15 },

    // Trash items - minimal sizes
    { sellValue: RARITY_POINTS.Trash, name: "Bone", rarity: "Trash", size: 15, weight: 0.2 },
    { sellValue: RARITY_POINTS.Trash, name: "Broken Guitar", rarity: "Trash", size: 100, weight: 4 },
    { sellValue: RARITY_POINTS.Trash, name: "Branch", rarity: "Trash", size: 40, weight: 0.3 },
    { sellValue: RARITY_POINTS.Trash, name: "Drink Rings", rarity: "Trash", size: 10, weight: 0.1 },
    { sellValue: RARITY_POINTS.Trash, name: "Plastic Bag", rarity: "Trash", size: 25, weight: 0.01 },
    { sellValue: RARITY_POINTS.Trash, name: "Soda Can", rarity: "Trash", size: 12, weight: 0.1 },
    { sellValue: RARITY_POINTS.Trash, name: "Weed", rarity: "Trash", size: 20, weight: 0.05 },
    { sellValue: RARITY_POINTS.Trash, name: "Old Boot", rarity: "Trash", size: 30, weight: 0.5 },
    { sellValue: RARITY_POINTS.Trash, name: "Rusty Can", rarity: "Trash", size: 15, weight: 0.2 },
    { sellValue: RARITY_POINTS.Trash, name: "Old Tire", rarity: "Trash", size: 50, weight: 1.5 },
    { sellValue: RARITY_POINTS.Trash, name: "Fishing Net", rarity: "Trash", size: 100, weight: 2 },
    { sellValue: RARITY_POINTS.Trash, name: "Plastic Bottle", rarity: "Trash", size: 20, weight: 0.3 },
    { sellValue: RARITY_POINTS.Trash, name: "Old Shoe", rarity: "Trash", size: 25, weight: 0.4 },
    { sellValue: RARITY_POINTS.Trash, name: "Cigarette Butt", rarity: "Trash", size: 1, weight: 0.001 },
    { sellValue: RARITY_POINTS.Trash, name: "Bottle Cap", rarity: "Trash", size: 2, weight: 0.001 },
];
