import { Adventure } from "./index";
import { pickRandom } from "../utils/misc";

const atlantisItems = [
    "pearl trident",
    "coral crown",
    "ancient conch",
    "sea crystal",
    "mermaid's tear",
    "sunken idol",
    "kelp amulet",
    "shell necklace",
    "starfish brooch",
    "oceanic tablet",
];
const atlantisEnemies = [
    "sea serpent",
    "kraken",
    "pirate diver",
    "giant eel",
    "merfolk guardian",
    "shark swarm",
    "coral golem",
    "jellyfish cloud",
    "abyssal horror",
    "rogue submarine",
];
const atlantisLocations = [
    "sunken temple",
    "coral reef",
    "deep trench",
    "kelp forest",
    "crystal cave",
    "shipwreck",
    "bubble dome",
    "tidal vent",
    "ocean floor",
    "lost plaza",
];
const atlantisEvents = [
    "tidal wave",
    "whirlpool",
    "bioluminescent bloom",
    "volcanic vent",
    "seaquake",
    "treasure rumor",
    "storm surge",
    "mysterious current",
    "singing whales",
    "sunken festival",
];

export const atlantisAdventures: Adventure[] = [
    {
        description: () => `A ${pickRandom(atlantisEvents)} stirs the ${pickRandom(atlantisLocations)}, adventurers dive for ancient secrets.`,
        winMessages: [
            name => `${name} finds a ${pickRandom(atlantisItems)} in the depths.`,
            name => `${name} defeats the ${pickRandom(atlantisEnemies)} and claims a ${pickRandom(atlantisItems)}.`,
            name => `${name} uncovers a lost chamber in the ${pickRandom(atlantisLocations)}.`,
            name => `${name} discovers a map etched on a ${pickRandom(atlantisItems)}.`,
            name => `${name} tames a ${pickRandom(atlantisEnemies)} and rides it through the ${pickRandom(atlantisLocations)}.`,
            name => `${name} solves the riddle of the ${pickRandom(atlantisLocations)}.`,
            name => `${name} is gifted a ${pickRandom(atlantisItems)} by a grateful merfolk.`,
            name => `${name} finds a hidden cache of ${pickRandom(atlantisItems)}.`,
            name => `${name} is blessed by the spirits of the ${pickRandom(atlantisLocations)}.`,
            name => `${name} escapes a trap and finds a ${pickRandom(atlantisItems)}.`,
        ],
        loseMessages: [
            name => `${name} is swept away by the ${pickRandom(atlantisEvents)}.`,
            name => `${name} is attacked by the ${pickRandom(atlantisEnemies)} and must retreat.`,
            name => `${name} gets lost in the ${pickRandom(atlantisLocations)} and finds nothing.`,
            name => `${name} is caught in a ${pickRandom(atlantisEvents)} and loses precious air.`,
            name => `${name} is tricked by a ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is trapped in a collapsing ${pickRandom(atlantisLocations)}.`,
            name => `${name} is cursed by a ${pickRandom(atlantisItems)}.`,
            name => `${name} is blinded by a ${pickRandom(atlantisEvents)}.`,
            name => `${name} is chased away by a ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is exhausted and must surface before finding anything.`,
        ],
    },
    {
        description: () => `The gates of the ${pickRandom(atlantisLocations)} open, revealing mysteries and dangers.`,
        winMessages: [
            name => `${name} unlocks the secrets of the ${pickRandom(atlantisLocations)}.`,
            name => `${name} finds a legendary ${pickRandom(atlantisItems)}.`,
            name => `${name} outsmarts a ${pickRandom(atlantisEnemies)} and escapes with treasure.`,
            name => `${name} deciphers ancient runes on a ${pickRandom(atlantisItems)}.`,
            name => `${name} is guided by a school of glowing fish to a hidden vault.`,
            name => `${name} discovers a portal to another realm in the ${pickRandom(atlantisLocations)}.`,
            name => `${name} is rewarded by the sea for bravery with a ${pickRandom(atlantisItems)}.`,
            name => `${name} finds a message in a bottle leading to riches.`,
            name => `${name} befriends a ${pickRandom(atlantisEnemies)} who shares a secret.`,
            name => `${name} finds a rare artifact in the ${pickRandom(atlantisLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is lost in the labyrinthine ${pickRandom(atlantisLocations)}.`,
            name => `${name} is ensnared by a ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is caught in a sudden ${pickRandom(atlantisEvents)}.`,
            name => `${name} is deceived by illusions in the ${pickRandom(atlantisLocations)}.`,
            name => `${name} is forced to flee from a ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is overwhelmed by the pressure of the deep.`,
            name => `${name} is separated from the group and finds nothing.`,
            name => `${name} is lured away by a false trail of ${pickRandom(atlantisItems)}.`,
            name => `${name} is struck by fear and cannot proceed.`,
            name => `${name} is caught in a net and must cut free, losing time.`,
        ],
    },
    {
        description: () => `A rumor of a ${pickRandom(atlantisItems)} hidden in the ${pickRandom(atlantisLocations)} spreads among adventurers.`,
        winMessages: [
            name => `${name} follows the clues and finds the fabled ${pickRandom(atlantisItems)}.`,
            name => `${name} braves the ${pickRandom(atlantisEvents)} and succeeds.`,
            name => `${name} solves the puzzle of the ${pickRandom(atlantisLocations)}.`,
            name => `${name} is aided by a mysterious figure in the deep.`,
            name => `${name} finds a chest full of ${pickRandom(atlantisItems)}.`,
            name => `${name} discovers a shortcut through the ${pickRandom(atlantisLocations)}.`,
            name => `${name} outwits a ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is granted a wish by a sea spirit.`,
            name => `${name} finds a hidden alcove with ancient treasures.`,
            name => `${name} returns with a story and a ${pickRandom(atlantisItems)}.`,
        ],
        loseMessages: [
            name => `${name} is misled by false rumors and finds nothing.`,
            name => `${name} is blocked by a ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is caught in a dangerous ${pickRandom(atlantisEvents)}.`,
            name => `${name} is trapped in a maze of coral.`,
            name => `${name} is forced to turn back by a lack of air.`,
            name => `${name} is distracted by a mirage of riches.`,
            name => `${name} is injured by a hidden trap.`,
            name => `${name} is delayed by a stubborn ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is swept away by a strong current.`,
            name => `${name} is left empty-handed after a long search.`,
        ],
    },
    {
        description: () => `A festival erupts in the ${pickRandom(atlantisLocations)}, drawing adventurers from afar.`,
        winMessages: [
            name => `${name} wins a contest and is awarded a ${pickRandom(atlantisItems)}.`,
            name => `${name} impresses the locals and receives a rare gift.`,
            name => `${name} dances with merfolk and learns a secret.`,
            name => `${name} finds a lost artifact during the festivities.`,
            name => `${name} is chosen as guest of honor and receives a ${pickRandom(atlantisItems)}.`,
            name => `${name} uncovers a hidden chamber beneath the plaza.`,
            name => `${name} is blessed by the festival's spirit.`,
            name => `${name} wins a riddle contest and earns a ${pickRandom(atlantisItems)}.`,
            name => `${name} discovers a forgotten tradition that leads to treasure.`,
            name => `${name} is guided to a secret vault by a friendly local.`,
        ],
        loseMessages: [
            name => `${name} is overwhelmed by the crowd and loses track of time.`,
            name => `${name} is pickpocketed by a sneaky ${pickRandom(atlantisEnemies)}.`,
            name => `${name} eats something strange and feels ill.`,
            name => `${name} is caught in a prank gone wrong.`,
            name => `${name} is distracted and misses the main event.`,
            name => `${name} is denied entry to the inner circle.`,
            name => `${name} is caught in a sudden downpour and must leave.`,
            name => `${name} is challenged to a duel and loses.`,
            name => `${name} is tricked by a clever local.`,
            name => `${name} is swept away by the excitement and finds nothing.`,
        ],
    },
    {
        description: () => `A ${pickRandom(atlantisEnemies)} guards the entrance to the ${pickRandom(atlantisLocations)}.`,
        winMessages: [
            name => `${name} sneaks past the ${pickRandom(atlantisEnemies)} unnoticed.`,
            name => `${name} defeats the guardian and enters the ${pickRandom(atlantisLocations)}.`,
            name => `${name} bribes the ${pickRandom(atlantisEnemies)} with a shiny trinket.`,
            name => `${name} distracts the ${pickRandom(atlantisEnemies)} and slips by.`,
            name => `${name} befriends the guardian and is allowed entry.`,
            name => `${name} finds a secret passage around the ${pickRandom(atlantisEnemies)}.`,
            name => `${name} uses a clever disguise to fool the ${pickRandom(atlantisEnemies)}.`,
            name => `${name} waits for the right moment and dashes inside.`,
            name => `${name} is aided by a mysterious ally.`,
            name => `${name} overcomes the challenge and finds a ${pickRandom(atlantisItems)}.`,
        ],
        loseMessages: [
            name => `${name} is spotted by the ${pickRandom(atlantisEnemies)} and chased away.`,
            name => `${name} is caught in a trap set by the guardian.`,
            name => `${name} is too slow and the entrance closes.`,
            name => `${name} is forced to retreat by the fierce ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is outsmarted by the guardian.`,
            name => `${name} is injured in the attempt and must withdraw.`,
            name => `${name} is blocked by an impenetrable barrier.`,
            name => `${name} is distracted and loses the opportunity.`,
            name => `${name} is tricked by a decoy.`,
            name => `${name} is caught in a net and must escape empty-handed.`,
        ],
    },
    {
        description: () => `A mysterious current pulls adventurers toward the ${pickRandom(atlantisLocations)}.`,
        winMessages: [
            name => `${name} rides the current to a hidden grotto.`,
            name => `${name} discovers a cache of ${pickRandom(atlantisItems)}.`,
            name => `${name} finds a shortcut to the heart of Atlantis.`,
            name => `${name} is guided by dolphins to safety and treasure.`,
            name => `${name} discovers a new species of glowing fish.`,
            name => `${name} finds a message carved into the rock.`,
            name => `${name} is swept into a secret chamber.`,
            name => `${name} finds a rare plant with magical properties.`,
            name => `${name} is led to a sunken ship full of riches.`,
            name => `${name} emerges in a forgotten plaza with a ${pickRandom(atlantisItems)}.`,
        ],
        loseMessages: [
            name => `${name} is swept away and separated from the group.`,
            name => `${name} is caught in a whirlpool and loses gear.`,
            name => `${name} is stranded in a dark cavern.`,
            name => `${name} is battered by rocks and must retreat.`,
            name => `${name} is lost in a maze of tunnels.`,
            name => `${name} is disoriented and finds nothing.`,
            name => `${name} is attacked by a lurking ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is trapped by falling debris.`,
            name => `${name} is forced to abandon the search.`,
            name => `${name} is exhausted by the struggle and must rest.`,
        ],
    },
    {
        description: () => `A legend speaks of a ${pickRandom(atlantisItems)} hidden in the ${pickRandom(atlantisLocations)}.`,
        winMessages: [
            name => `${name} deciphers the legend and finds the treasure.`,
            name => `${name} braves the dangers and claims the ${pickRandom(atlantisItems)}.`,
            name => `${name} is guided by ancient spirits to the prize.`,
            name => `${name} solves the mystery of the ${pickRandom(atlantisLocations)}.`,
            name => `${name} finds a hidden door leading to riches.`,
            name => `${name} is aided by a wise old merfolk.`,
            name => `${name} discovers a forgotten ritual that reveals the way.`,
            name => `${name} finds a map leading to the ${pickRandom(atlantisItems)}.`,
            name => `${name} is rewarded for persistence with a rare find.`,
            name => `${name} returns triumphant with the legendary artifact.`,
        ],
        loseMessages: [
            name => `${name} is misled by false clues.`,
            name => `${name} is blocked by a powerful curse.`,
            name => `${name} is attacked by a jealous rival.`,
            name => `${name} is caught in a trap and must escape.`,
            name => `${name} is forced to turn back by a fierce guardian.`,
            name => `${name} is lost in the twisting passages.`,
            name => `${name} is deceived by illusions.`,
            name => `${name} is exhausted by the search.`,
            name => `${name} is swept away by a sudden current.`,
            name => `${name} is left empty-handed as the legend fades.`,
        ],
    },
    {
        description: () => `A volcanic vent erupts near the ${pickRandom(atlantisLocations)}, shaking the sea floor.`,
        winMessages: [
            name => `${name} braves the heat and finds a rare gem.`,
            name => `${name} discovers a new passage revealed by the eruption.`,
            name => `${name} collects valuable minerals from the vent.`,
            name => `${name} finds a fossilized artifact.`,
            name => `${name} is protected by a magical bubble.`,
            name => `${name} discovers a hidden ecosystem.`,
            name => `${name} finds a lost relic in the cooled lava.`,
            name => `${name} is guided by glowing creatures to safety.`,
            name => `${name} uncovers a secret chamber beneath the vent.`,
            name => `${name} escapes with a handful of precious stones.`,
        ],
        loseMessages: [
            name => `${name} is burned by the hot water and must retreat.`,
            name => `${name} is caught in a cloud of ash.`,
            name => `${name} is forced back by toxic fumes.`,
            name => `${name} is trapped by falling rocks.`,
            name => `${name} is separated from the group in the chaos.`,
            name => `${name} is blinded by steam.`,
            name => `${name} is chased away by a startled ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is injured by flying debris.`,
            name => `${name} is lost in the darkness.`,
            name => `${name} is forced to abandon the search as the vent erupts again.`,
        ],
    },
    {
        description: () => `A sunken ship is discovered near the ${pickRandom(atlantisLocations)}.`,
        winMessages: [
            name => `${name} finds a chest of gold in the wreck.`,
            name => `${name} discovers a captain's log with clues.`,
            name => `${name} retrieves a priceless artifact from the hold.`,
            name => `${name} finds a stash of rare ${pickRandom(atlantisItems)}.`,
            name => `${name} uncovers a hidden compartment full of jewels.`,
            name => `${name} is aided by a friendly octopus.`,
            name => `${name} finds a map to another treasure.`,
            name => `${name} discovers a magical compass.`,
            name => `${name} is guided by a ghostly crew member.`,
            name => `${name} escapes with a handful of ancient coins.`,
        ],
        loseMessages: [
            name => `${name} is trapped in the wreckage.`,
            name => `${name} is attacked by a lurking ${pickRandom(atlantisEnemies)}.`,
            name => `${name} is caught in a collapsing corridor.`,
            name => `${name} is forced to flee by a sudden leak.`,
            name => `${name} is lost in the maze of rooms.`,
            name => `${name} is frightened by ghostly whispers.`,
            name => `${name} is injured by sharp debris.`,
            name => `${name} is blocked by a locked door.`,
            name => `${name} is swept away by a strong current.`,
            name => `${name} is left empty-handed as the ship settles deeper.`,
        ],
    },
    {
        description: () => `A bioluminescent bloom lights up the ${pickRandom(atlantisLocations)}, revealing hidden wonders.`,
        winMessages: [
            name => `${name} finds a glowing ${pickRandom(atlantisItems)}.`,
            name => `${name} discovers a new species of luminous coral.`,
            name => `${name} is guided to treasure by the glowing lights.`,
            name => `${name} finds a hidden message in the patterns of light.`,
            name => `${name} is blessed by the spirits of the bloom.`,
            name => `${name} collects rare glowing pearls.`,
            name => `${name} uncovers a secret path illuminated by the bloom.`,
            name => `${name} is inspired by the beauty and finds a ${pickRandom(atlantisItems)}.`,
            name => `${name} meets a wise old merfolk who shares a secret.`,
            name => `${name} finds a rare plant with healing powers.`,
        ],
        loseMessages: [
            name => `${name} is blinded by the intense light.`,
            name => `${name} is distracted and loses track of time.`,
            name => `${name} is caught in a swarm of glowing jellyfish.`,
            name => `${name} is led astray by false trails of light.`,
            name => `${name} is overwhelmed by the beauty and forgets the mission.`,
            name => `${name} is stung by a hidden creature.`,
            name => `${name} is lost in the maze of glowing coral.`,
            name => `${name} is separated from the group by the bloom.`,
            name => `${name} is caught in a sudden current.`,
            name => `${name} is left empty-handed as the lights fade.`,
        ],
    },
];
