import { Adventure } from "./index";
import { pickRandom } from "../utils/misc";

const dinoItems = [
    "amber fossil",
    "stone spear",
    "dinosaur egg",
    "saber tooth necklace",
    "mammoth tusk",
    "flint knife",
    "feathered cloak",
    "ancient drum",
    "bone charm",
    "fire starter",
];
const dinoEnemies = [
    "velociraptor pack",
    "saber-tooth cat",
    "giant sloth",
    "dire wolf",
    "cave bear",
    "pterodactyl",
    "spinosaurus",
    "carnotaurus",
    "giant snake",
    "swarm of insects",
];
const dinoLocations = [
    "volcanic plain",
    "primeval forest",
    "river crossing",
    "cave system",
    "tar pit",
    "rocky bluff",
    "mossy glen",
    "ancient lake",
    "muddy marsh",
    "dinosaur nest",
];
const dinoEvents = [
    "earthquake",
    "volcanic eruption",
    "meteor shower",
    "flash flood",
    "stampede",
    "forest fire",
    "landslide",
    "solar eclipse",
    "predator hunt",
    "herd migration",
];
export const dinoAdventures: Adventure[] = [
    {
        description: () => `A ${pickRandom(dinoEvents)} shakes the ${pickRandom(dinoLocations)}, only the strongest survive in this ancient world.`,
        winMessages: [
            name => `${name} hunts and brings back a ${pickRandom(dinoItems)}.`,
            name => `${name} escapes the ${pickRandom(dinoEnemies)} and finds a hidden cave.`,
            name => `${name} discovers a rare ${pickRandom(dinoItems)} in the wilds.`,
        ],
        loseMessages: [
            name => `${name} is chased by the ${pickRandom(dinoEnemies)} and loses their supplies.`,
            name => `${name} is caught in a ${pickRandom(dinoEvents)} and must hide.`,
            name => `${name} is injured in the ${pickRandom(dinoLocations)} and must retreat.`,
        ],
    },
    {
        description: () => `In the heart of the ${pickRandom(dinoLocations)}, danger and opportunity lurk at every turn.`,
        winMessages: [
            name => `${name} befriends a wandering ${pickRandom(dinoEnemies)} and learns its secrets.`,
            name => `${name} finds a cache of ${pickRandom(dinoItems)} buried beneath ancient roots.`,
            name => `${name} outsmarts a ${pickRandom(dinoEnemies)} and claims its territory.`,
            name => `${name} discovers a shortcut through the ${pickRandom(dinoLocations)}.`,
            name => `${name} stumbles upon a herd migration and gathers rare resources.`,
            name => `${name} crafts a new tool from a ${pickRandom(dinoItems)}.`,
            name => `${name} finds shelter just in time before a ${pickRandom(dinoEvents)}.`,
            name => `${name} learns to mimic the calls of a ${pickRandom(dinoEnemies)}.`,
            name => `${name} uncovers a hidden spring in the ${pickRandom(dinoLocations)}.`,
            name => `${name} is gifted a ${pickRandom(dinoItems)} by a grateful tribe.`,
        ],
        loseMessages: [
            name => `${name} is ambushed by a ${pickRandom(dinoEnemies)} and barely escapes.`,
            name => `${name} gets lost in the ${pickRandom(dinoLocations)} for days.`,
            name => `${name} is caught in a sudden ${pickRandom(dinoEvents)} and loses precious time.`,
            name => `${name} drops their ${pickRandom(dinoItems)} while fleeing danger.`,
            name => `${name} is bitten by a venomous creature in the ${pickRandom(dinoLocations)}.`,
            name => `${name} is forced to abandon supplies during a ${pickRandom(dinoEvents)}.`,
            name => `${name} is outwitted by a cunning ${pickRandom(dinoEnemies)}.`,
            name => `${name} injures their foot on a sharp ${pickRandom(dinoItems)}.`,
            name => `${name} is separated from the group in the ${pickRandom(dinoLocations)}.`,
            name => `${name} is caught in a trap set by another survivor.`,
        ],
    },
    {
        description: () => `A mysterious signal echoes across the ${pickRandom(dinoLocations)}, drawing all creatures near.`,
        winMessages: [
            name => `${name} deciphers the signal and finds a hidden stash of ${pickRandom(dinoItems)}.`,
            name => `${name} uses the distraction to sneak past a ${pickRandom(dinoEnemies)}.`,
            name => `${name} discovers a new species near the ${pickRandom(dinoLocations)}.`,
            name => `${name} follows the signal to a safe haven.`,
            name => `${name} finds a lost companion and teams up for survival.`,
            name => `${name} learns a new survival skill from observing the ${pickRandom(dinoEnemies)}.`,
            name => `${name} finds edible plants growing after the ${pickRandom(dinoEvents)}.`,
            name => `${name} crafts a clever trap using a ${pickRandom(dinoItems)}.`,
            name => `${name} is guided by ancient cave paintings to safety.`,
            name => `${name} discovers a fossilized map in the ${pickRandom(dinoLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is lured into danger by the mysterious signal.`,
            name => `${name} is caught in a stampede caused by the signal.`,
            name => `${name} is attacked by a startled ${pickRandom(dinoEnemies)}.`,
            name => `${name} loses their way in the ${pickRandom(dinoLocations)}.`,
            name => `${name} is injured by falling debris during a ${pickRandom(dinoEvents)}.`,
            name => `${name} is forced to abandon their ${pickRandom(dinoItems)}.`,
            name => `${name} is trapped in a cave-in while exploring.`,
            name => `${name} is exhausted after chasing the signal all night.`,
            name => `${name} is drenched and cold after a sudden ${pickRandom(dinoEvents)}.`,
            name => `${name} is stalked by a relentless ${pickRandom(dinoEnemies)}.`,
        ],
    },
    {
        description: () => `Night falls over the ${pickRandom(dinoLocations)}, and the world comes alive with unseen threats.`,
        winMessages: [
            name => `${name} builds a roaring fire with a ${pickRandom(dinoItems)} to keep predators at bay.`,
            name => `${name} navigates by starlight and finds a safe resting spot.`,
            name => `${name} listens to the distant calls of a ${pickRandom(dinoEnemies)} and avoids danger.`,
            name => `${name} crafts a sturdy shelter from ancient trees.`,
            name => `${name} finds a hidden cache of food left by earlier explorers.`,
            name => `${name} learns to read the signs of the night sky.`,
            name => `${name} is protected by a friendly ${pickRandom(dinoEnemies)}.`,
            name => `${name} discovers a glowing fungus that lights the way.`,
            name => `${name} finds a lost artifact in the moonlight.`,
            name => `${name} is inspired by the beauty of the ${pickRandom(dinoLocations)} at night.`,
        ],
        loseMessages: [
            name => `${name} is startled by eerie noises and loses sleep.`,
            name => `${name} is bitten by insects swarming in the dark.`,
            name => `${name} is stalked by a nocturnal ${pickRandom(dinoEnemies)}.`,
            name => `${name} trips over a root and injures their ankle.`,
            name => `${name} is caught in a sudden downpour and drenched.`,
            name => `${name} loses their way in the darkness of the ${pickRandom(dinoLocations)}.`,
            name => `${name} is forced to abandon their camp after a ${pickRandom(dinoEvents)}.`,
            name => `${name} is robbed by another survivor under cover of night.`,
            name => `${name} is haunted by strange dreams and wakes up exhausted.`,
            name => `${name} is nearly caught by a prowling ${pickRandom(dinoEnemies)}.`,
        ],
    },
];
