import { Adventure } from "./index";
import { pickRandom } from "../utils/misc";

const egyptItems = [
    "golden scarab",
    "pharaoh's ring",
    "ankh amulet",
    "papyrus scroll",
    "sacred cat statue",
    "lapis lazuli necklace",
    "copper sickle",
    "sun disk",
    "canopic jar",
    "mummy's mask",
];
const egyptEnemies = [
    "mummy",
    "crocodile guardian",
    "scarab swarm",
    "desert bandit",
    "jackal priest",
    "cursed pharaoh",
    "sand wraith",
    "cobra",
    "tomb robber",
    "vulture spirit",
];
const egyptLocations = [
    "pyramid chamber",
    "Nile delta",
    "desert oasis",
    "sun temple",
    "buried tomb",
    "market bazaar",
    "sphinx shadow",
    "sacred obelisk",
    "catacomb",
    "pharaoh's palace",
];
const egyptEvents = [
    "sandstorm",
    "solar eclipse",
    "tomb collapse",
    "sacred festival",
    "mummy's curse",
    "river flood",
    "scorpion swarm",
    "mirage",
    "ancient prophecy",
    "treasure hunt",
];
export const egyptAdventures: Adventure[] = [
    {
        description: () => `A ${pickRandom(egyptEvents)} strikes the ${pickRandom(egyptLocations)}, explorers seek lost relics of the pharaohs.`,
        winMessages: [
            name => `${name} uncovers a ${pickRandom(egyptItems)} in the sand.`,
            name => `${name} defeats the ${pickRandom(egyptEnemies)} and claims a ${pickRandom(egyptItems)}.`,
            name => `${name} solves a riddle and is rewarded at the ${pickRandom(egyptLocations)}.`,
            name => `${name} is guided by a local through the ${pickRandom(egyptLocations)} and finds a ${pickRandom(egyptItems)}.`,
            name => `${name} braves a ${pickRandom(egyptEvents)} and discovers a hidden chamber.`,
            name => `${name} negotiates with a ${pickRandom(egyptEnemies)} for safe passage and a ${pickRandom(egyptItems)}.`,
            name => `${name} finds a map to the ${pickRandom(egyptLocations)} and retrieves a ${pickRandom(egyptItems)}.`,
            name => `${name} is blessed by a priest during a ${pickRandom(egyptEvents)}.`,
            name => `${name} wins a contest at the ${pickRandom(egyptLocations)} and receives a ${pickRandom(egyptItems)}.`,
            name => `${name} discovers a secret inscription revealing the location of a ${pickRandom(egyptItems)}.`,
        ],
        loseMessages: [
            name => `${name} is cursed by the ${pickRandom(egyptEnemies)} and must retreat.`,
            name => `${name} is lost in the ${pickRandom(egyptLocations)} and finds nothing.`,
            name => `${name} is caught in a ${pickRandom(egyptEvents)} and injured.`,
            name => `${name} is ambushed by a ${pickRandom(egyptEnemies)} and loses their supplies.`,
            name => `${name} is deceived by a false guide at the ${pickRandom(egyptLocations)}.`,
            name => `${name} is trapped by a collapsing wall during a ${pickRandom(egyptEvents)}.`,
            name => `${name} is bitten by a ${pickRandom(egyptEnemies)} and falls ill.`,
            name => `${name} is denied entry to the ${pickRandom(egyptLocations)} by a suspicious guard.`,
            name => `${name} loses a precious ${pickRandom(egyptItems)} in the chaos of a ${pickRandom(egyptEvents)}.`,
            name => `${name} is exhausted by the relentless heat of the ${pickRandom(egyptLocations)}.`,
        ],
    },
    {
        description: () => `In the shadow of the ${pickRandom(egyptLocations)}, a ${pickRandom(egyptEvents)} challenges all who enter.`,
        winMessages: [
            name => `${name} discovers a hidden ${pickRandom(egyptItems)} beneath ancient stones.`,
            name => `${name} outsmarts a ${pickRandom(egyptEnemies)} and escapes with treasure.`,
            name => `${name} is blessed by a priest at the ${pickRandom(egyptLocations)}.`,
            name => `${name} finds a map to the ${pickRandom(egyptLocations)}.`,
            name => `${name} tames a wild ${pickRandom(egyptEnemies)} and gains its loyalty.`,
            name => `${name} deciphers a prophecy during a ${pickRandom(egyptEvents)}.`,
            name => `${name} receives a ${pickRandom(egyptItems)} from a grateful merchant.`,
            name => `${name} navigates a ${pickRandom(egyptEvents)} and finds shelter.`,
            name => `${name} is guided by a sacred ${pickRandom(egyptItems)}.`,
            name => `${name} wins a contest at the ${pickRandom(egyptLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is ambushed by a ${pickRandom(egyptEnemies)} in the night.`,
            name => `${name} loses their way in the ${pickRandom(egyptLocations)}.`,
            name => `${name} is struck by a sudden ${pickRandom(egyptEvents)}.`,
            name => `${name} is robbed by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is denied entry to the ${pickRandom(egyptLocations)}.`,
            name => `${name} is poisoned by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is caught in a trap set during a ${pickRandom(egyptEvents)}.`,
            name => `${name} is tricked by a false guide at the ${pickRandom(egyptLocations)}.`,
            name => `${name} loses a precious ${pickRandom(egyptItems)} in the sand.`,
            name => `${name} is exhausted by the relentless ${pickRandom(egyptEvents)}.`,
        ],
    },
    {
        description: () => `A secret passage in the ${pickRandom(egyptLocations)} promises riches, but danger lurks with every step.`,
        winMessages: [
            name => `${name} unlocks a chamber filled with ${pickRandom(egyptItems)}.`,
            name => `${name} defeats a ${pickRandom(egyptEnemies)} and finds a clue.`,
            name => `${name} is aided by a mysterious stranger during a ${pickRandom(egyptEvents)}.`,
            name => `${name} solves the puzzle of the ${pickRandom(egyptLocations)}.`,
            name => `${name} discovers a lost ${pickRandom(egyptItems)}.`,
            name => `${name} escapes a collapsing tunnel during a ${pickRandom(egyptEvents)}.`,
            name => `${name} is rewarded by the spirits of the ${pickRandom(egyptLocations)}.`,
            name => `${name} finds a safe path through a ${pickRandom(egyptEvents)}.`,
            name => `${name} is granted wisdom by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} wins a wager at the ${pickRandom(egyptLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is trapped by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is blinded by a sudden ${pickRandom(egyptEvents)}.`,
            name => `${name} is betrayed by a companion at the ${pickRandom(egyptLocations)}.`,
            name => `${name} is bitten by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is caught stealing a ${pickRandom(egyptItems)}.`,
            name => `${name} is swept away by a ${pickRandom(egyptEvents)}.`,
            name => `${name} is cursed for disturbing the ${pickRandom(egyptLocations)}.`,
            name => `${name} loses their supplies in a ${pickRandom(egyptEvents)}.`,
            name => `${name} is chased away by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is denied a blessing at the ${pickRandom(egyptLocations)}.`,
        ],
    },
    {
        description: () => `Rumors of a ${pickRandom(egyptItems)} hidden in the ${pickRandom(egyptLocations)} draw adventurers from afar.`,
        winMessages: [
            name => `${name} braves a ${pickRandom(egyptEvents)} and finds the legendary ${pickRandom(egyptItems)}.`,
            name => `${name} is protected by a ${pickRandom(egyptEnemies)} spirit.`,
            name => `${name} is honored at a ${pickRandom(egyptLocations)} ceremony.`,
            name => `${name} discovers a secret exit during a ${pickRandom(egyptEvents)}.`,
            name => `${name} is gifted a rare ${pickRandom(egyptItems)} by a local.`,
            name => `${name} wins a duel against a ${pickRandom(egyptEnemies)}.`,
            name => `${name} finds a hidden message in the ${pickRandom(egyptLocations)}.`,
            name => `${name} is saved by a timely ${pickRandom(egyptEvents)}.`,
            name => `${name} is chosen by the gods at the ${pickRandom(egyptLocations)}.`,
            name => `${name} uncovers a cache of ${pickRandom(egyptItems)}.`,
        ],
        loseMessages: [
            name => `${name} is caught in a feud between ${pickRandom(egyptEnemies)}.`,
            name => `${name} is lost during a ${pickRandom(egyptEvents)}.`,
            name => `${name} is denied help at the ${pickRandom(egyptLocations)}.`,
            name => `${name} is injured by a trap set by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is haunted by a ${pickRandom(egyptEnemies)}.`,
            name => `${name} is forced to abandon a ${pickRandom(egyptItems)}.`,
            name => `${name} is weakened by a ${pickRandom(egyptEvents)}.`,
            name => `${name} is deceived by a merchant at the ${pickRandom(egyptLocations)}.`,
            name => `${name} is stranded after a ${pickRandom(egyptEvents)}.`,
            name => `${name} is outwitted by a rival at the ${pickRandom(egyptLocations)}.`,
        ],
    },
];
