import { Adventure } from "./index";
import { pickRandom } from "../utils/misc";

const pirateItems = [
    "jeweled cutlass",
    "ancient map",
    "gold doubloon",
    "enchanted compass",
    "pirate hat",
    "silver locket",
    "spyglass",
    "rum bottle",
    "cursed amulet",
    "pearl necklace",
];
const pirateEnemies = [
    "kraken",
    "rival pirates",
    "naval patrol",
    "sea witch",
    "ghost ship",
    "mutinous crew",
    "giant crab",
    "sirens",
    "storm spirits",
    "cursed skeletons",
];
const pirateLocations = [
    "treasure island",
    "hidden cove",
    "stormy sea",
    "abandoned fort",
    "sunken wreck",
    "mysterious reef",
    "foggy bay",
    "pirate port",
    "volcanic atoll",
    "coral lagoon",
];
const pirateEvents = [
    "tempest",
    "mutiny",
    "sea monster attack",
    "fog bank",
    "treasure rumor",
    "cannon barrage",
    "ghostly apparition",
    "shipwreck",
    "rival chase",
    "eclipse",
];

export const pirateAdventures: Adventure[] = [
    {
        description: () =>
            `A ${pickRandom(pirateEvents)} threatens the crew near the ${pickRandom(pirateLocations)}, but a map hints at hidden treasure.`,
        winMessages: [
            name => `${name} finds a ${pickRandom(pirateItems)} buried in the sand.`,
            name => `${name} defeats ${pickRandom(pirateEnemies)} and claims a ${pickRandom(pirateItems)}.`,
            name => `${name} navigates the ${pickRandom(pirateLocations)} and discovers a secret hoard.`,
            name => `${name} outsmarts ${pickRandom(pirateEnemies)} and escapes with a ${pickRandom(pirateItems)}.`,
            name => `${name} braves the ${pickRandom(pirateEvents)} and finds a ${pickRandom(pirateItems)}.`,
            name => `${name} follows a clue to a hidden ${pickRandom(pirateItems)} in the ${pickRandom(pirateLocations)}.`,
            name => `${name} uncovers a ${pickRandom(pirateItems)} after surviving a ${pickRandom(pirateEvents)}.`,
            name => `${name} discovers a stash of ${pickRandom(pirateItems)} guarded by ${pickRandom(pirateEnemies)}.`,
            name => `${name} uses an ${pickRandom(pirateItems)} to unlock a chest in the ${pickRandom(pirateLocations)}.`,
            name => `${name} and the crew celebrate after finding a ${pickRandom(pirateItems)} during the ${pickRandom(pirateEvents)}.`,
        ],
        loseMessages: [
            name => `${name} is swept overboard during the ${pickRandom(pirateEvents)}.`,
            name => `${name} is captured by ${pickRandom(pirateEnemies)}.`,
            name => `${name} gets lost in the ${pickRandom(pirateLocations)} and finds nothing.`,
            name => `${name} is tricked by a ${pickRandom(pirateEnemies)} and loses their ${pickRandom(pirateItems)}.`,
            name => `${name} is stranded on ${pickRandom(pirateLocations)} after a ${pickRandom(pirateEvents)}.`,
            name => `${name} is cursed by a ${pickRandom(pirateItems)} and must abandon the quest.`,
            name => `${name} is forced to retreat by ${pickRandom(pirateEnemies)}.`,
            name => `${name} loses the map to the ${pickRandom(pirateItems)} in the chaos of a ${pickRandom(pirateEvents)}.`,
            name => `${name} is marooned by a mutinous crew at ${pickRandom(pirateLocations)}.`,
            name => `${name} is caught in a trap set by ${pickRandom(pirateEnemies)} and loses everything.`,
        ],
    },
    {
        description: () =>
            `Rumors of a ${pickRandom(pirateItems)} hidden in the ${pickRandom(pirateLocations)} spark a race against ${pickRandom(pirateEnemies)}.`,
        winMessages: [
            name => `${name} finds the legendary ${pickRandom(pirateItems)} before ${pickRandom(pirateEnemies)}.`,
            name => `${name} outpaces ${pickRandom(pirateEnemies)} and secures a ${pickRandom(pirateItems)}.`,
            name => `${name} solves the riddle of the ${pickRandom(pirateLocations)} and uncovers a ${pickRandom(pirateItems)}.`,
            name => `${name} bribes a local to reveal the ${pickRandom(pirateItems)}'s hiding place.`,
            name => `${name} sneaks past ${pickRandom(pirateEnemies)} and grabs a ${pickRandom(pirateItems)}.`,
            name => `${name} uses a ${pickRandom(pirateItems)} to unlock a secret vault.`,
            name => `${name} and the crew celebrate after finding a ${pickRandom(pirateItems)} in the ${pickRandom(pirateLocations)}.`,
            name => `${name} tricks ${pickRandom(pirateEnemies)} into leaving the ${pickRandom(pirateItems)} unguarded.`,
            name => `${name} discovers a hidden passage in the ${pickRandom(pirateLocations)} leading to a ${pickRandom(pirateItems)}.`,
            name => `${name} wins a duel with ${pickRandom(pirateEnemies)} and claims the ${pickRandom(pirateItems)}.`,
        ],
        loseMessages: [
            name => `${name} is ambushed by ${pickRandom(pirateEnemies)} and loses the race.`,
            name => `${name} is trapped in the ${pickRandom(pirateLocations)} and misses the treasure.`,
            name => `${name} is double-crossed by a supposed ally and loses the ${pickRandom(pirateItems)}.`,
            name => `${name} is caught in a landslide at the ${pickRandom(pirateLocations)}.`,
            name => `${name} is outsmarted by ${pickRandom(pirateEnemies)} and leaves empty-handed.`,
            name => `${name} is poisoned by a cursed ${pickRandom(pirateItems)}.`,
            name => `${name} is forced to surrender to ${pickRandom(pirateEnemies)}.`,
            name => `${name} is lost in a maze of tunnels beneath the ${pickRandom(pirateLocations)}.`,
            name => `${name} is swept away by a sudden ${pickRandom(pirateEvents)}.`,
            name => `${name} is left behind as the crew flees from ${pickRandom(pirateEnemies)}.`,
        ],
    },
    {
        description: () =>
            `A mysterious ${pickRandom(pirateItems)} is said to control the tides at ${pickRandom(pirateLocations)}, but ${pickRandom(pirateEnemies)} guard it fiercely.`,
        winMessages: [
            name => `${name} steals the ${pickRandom(pirateItems)} from under the nose of ${pickRandom(pirateEnemies)}.`,
            name => `${name} uses cunning to distract ${pickRandom(pirateEnemies)} and grabs the ${pickRandom(pirateItems)}.`,
            name => `${name} solves the puzzle of the ${pickRandom(pirateLocations)} and claims the ${pickRandom(pirateItems)}.`,
            name => `${name} braves the wrath of ${pickRandom(pirateEnemies)} to seize the ${pickRandom(pirateItems)}.`,
            name => `${name} finds a secret entrance to the ${pickRandom(pirateLocations)} and escapes with the ${pickRandom(pirateItems)}.`,
            name => `${name} uses a decoy to fool ${pickRandom(pirateEnemies)} and takes the ${pickRandom(pirateItems)}.`,
            name => `${name} enlists help from a local to bypass ${pickRandom(pirateEnemies)}.`,
            name => `${name} survives a ${pickRandom(pirateEvents)} and finds the ${pickRandom(pirateItems)} washed ashore.`,
            name => `${name} outwits a trap set by ${pickRandom(pirateEnemies)} and secures the ${pickRandom(pirateItems)}.`,
            name => `${name} and the crew celebrate after retrieving the ${pickRandom(pirateItems)} from ${pickRandom(pirateLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is caught by ${pickRandom(pirateEnemies)} and thrown in the brig.`,
            name => `${name} is lost in the labyrinthine ${pickRandom(pirateLocations)}.`,
            name => `${name} is cursed by the ${pickRandom(pirateItems)} and flees in terror.`,
            name => `${name} is betrayed by a crew member to ${pickRandom(pirateEnemies)}.`,
            name => `${name} is injured during a skirmish with ${pickRandom(pirateEnemies)}.`,
            name => `${name} is swept away by a sudden ${pickRandom(pirateEvents)}.`,
            name => `${name} is forced to abandon the quest after losing the map to the ${pickRandom(pirateItems)}.`,
            name => `${name} is outnumbered by ${pickRandom(pirateEnemies)} and retreats.`,
            name => `${name} is trapped by a collapsing tunnel in the ${pickRandom(pirateLocations)}.`,
            name => `${name} is left behind as the crew escapes from ${pickRandom(pirateEnemies)}.`,
        ],
    },
    {
        description: () =>
            `During a ${pickRandom(pirateEvents)}, a clue to a lost ${pickRandom(pirateItems)} surfaces at ${pickRandom(pirateLocations)}.`,
        winMessages: [
            name => `${name} deciphers the clue and finds the ${pickRandom(pirateItems)}.`,
            name => `${name} braves the ${pickRandom(pirateEvents)} and uncovers the ${pickRandom(pirateItems)}.`,
            name => `${name} outsmarts ${pickRandom(pirateEnemies)} to claim the ${pickRandom(pirateItems)}.`,
            name => `${name} follows a trail through the ${pickRandom(pirateLocations)} to a hidden ${pickRandom(pirateItems)}.`,
            name => `${name} and the crew celebrate after retrieving the ${pickRandom(pirateItems)}.`,
            name => `${name} uses a ${pickRandom(pirateItems)} to unlock a secret compartment.`,
            name => `${name} tricks ${pickRandom(pirateEnemies)} into revealing the ${pickRandom(pirateItems)}'s location.`,
            name => `${name} finds the ${pickRandom(pirateItems)} inside a sunken chest at ${pickRandom(pirateLocations)}.`,
            name => `${name} solves a riddle left by ancient pirates and claims the ${pickRandom(pirateItems)}.`,
            name => `${name} wins a wager with ${pickRandom(pirateEnemies)} and takes the ${pickRandom(pirateItems)}.`,
        ],
        loseMessages: [
            name => `${name} is swept away by the ${pickRandom(pirateEvents)} before finding the treasure.`,
            name => `${name} is deceived by a false clue planted by ${pickRandom(pirateEnemies)}.`,
            name => `${name} is trapped in a cave-in at ${pickRandom(pirateLocations)}.`,
            name => `${name} is forced to abandon the search after a run-in with ${pickRandom(pirateEnemies)}.`,
            name => `${name} is cursed by the ${pickRandom(pirateItems)} and loses their way.`,
            name => `${name} is marooned at ${pickRandom(pirateLocations)} by a mutinous crew.`,
            name => `${name} is caught in a storm and loses the map to the ${pickRandom(pirateItems)}.`,
            name => `${name} is outwitted by ${pickRandom(pirateEnemies)} and leaves empty-handed.`,
            name => `${name} is injured during a brawl over the ${pickRandom(pirateItems)}.`,
            name => `${name} is left behind as the crew flees from ${pickRandom(pirateEnemies)}.`,
        ],
    },
];
