import { Adventure } from "./index";
import { pickRandom } from "../utils/misc";

const postApocItems = [
    "rusted rifle",
    "mutant serum",
    "makeshift armor",
    "ancient battery",
    "water purifier",
    "scrap toolkit",
    "pre-war medkit",
    "solar charger",
    "rad suit",
    "encrypted holotape",
];
const postApocEnemies = [
    "mutant hounds",
    "raider gang",
    "feral ghouls",
    "radiation zombies",
    "wasteland bandits",
    "giant scorpions",
    "rogue synths",
    "toxic slimes",
    "cannibal cultists",
    "stormriders",
];
const postApocLocations = [
    "ruined city",
    "abandoned bunker",
    "crashed convoy",
    "toxic marsh",
    "collapsed overpass",
    "underground metro",
    "deserted mall",
    "radioactive crater",
    "flooded vault",
    "wasteland outpost",
];
const postApocEvents = [
    "radiation storm",
    "acid rain",
    "mutant stampede",
    "power surge",
    "supply drop",
    "dust tornado",
    "solar flare",
    "raider ambush",
    "generator meltdown",
    "mysterious broadcast",
];
export const postApocAdventures: Adventure[] = [
    {
        description: () =>
            `A ${pickRandom(postApocEvents)} sweeps through the ${pickRandom(postApocLocations)}, survivors scramble for precious resources.`,
        winMessages: [
            name => `${name} scavenges a ${pickRandom(postApocItems)} from the ruins.`,
            name => `${name} defeats ${pickRandom(postApocEnemies)} and claims a ${pickRandom(postApocItems)}.`,
            name => `${name} finds a hidden cache in the ${pickRandom(postApocLocations)}.`,
            name => `${name} repairs a ${pickRandom(postApocItems)} using parts from a ${pickRandom(postApocLocations)}.`,
            name => `${name} barters with ${pickRandom(postApocEnemies)} for a ${pickRandom(postApocItems)}.`,
            name => `${name} discovers a working ${pickRandom(postApocItems)} during a ${pickRandom(postApocEvents)}.`,
            name => `${name} sneaks past ${pickRandom(postApocEnemies)} and grabs a ${pickRandom(postApocItems)}.`,
            name => `${name} deciphers a ${pickRandom(postApocItems)} in the ${pickRandom(postApocLocations)}.`,
            name => `${name} finds shelter in a ${pickRandom(postApocLocations)} and recovers supplies.`,
            name => `${name} hacks a ${pickRandom(postApocItems)} to open a vault in the ${pickRandom(postApocLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is ambushed by ${pickRandom(postApocEnemies)} and loses supplies.`,
            name => `${name} is caught in a ${pickRandom(postApocEvents)} and must retreat.`,
            name => `${name} is injured exploring the ${pickRandom(postApocLocations)}.`,
            name => `${name} drops a ${pickRandom(postApocItems)} while fleeing from ${pickRandom(postApocEnemies)}.`,
            name => `${name} is trapped in a ${pickRandom(postApocLocations)} during a ${pickRandom(postApocEvents)}.`,
            name => `${name} is robbed by ${pickRandom(postApocEnemies)} and left with nothing.`,
            name => `${name} is exposed to a ${pickRandom(postApocEvents)} and falls ill.`,
            name => `${name} is forced to abandon a ${pickRandom(postApocItems)} to escape danger.`,
            name => `${name} is outsmarted by ${pickRandom(postApocEnemies)} in the ${pickRandom(postApocLocations)}.`,
            name => `${name} is caught in a crossfire between ${pickRandom(postApocEnemies)} and loses gear.`,
        ],
    },
    {
        description: () =>
            `In the ${pickRandom(postApocLocations)}, rumors spread of a lost ${pickRandom(postApocItems)} guarded by ${pickRandom(postApocEnemies)}.`,
        winMessages: [
            name => `${name} sneaks past ${pickRandom(postApocEnemies)} and retrieves the ${pickRandom(postApocItems)}.`,
            name => `${name} outwits a group of ${pickRandom(postApocEnemies)} to claim a ${pickRandom(postApocItems)}.`,
            name => `${name} discovers a map to a ${pickRandom(postApocItems)} in the ${pickRandom(postApocLocations)}.`,
            name => `${name} disables a trap set by ${pickRandom(postApocEnemies)} and finds supplies.`,
            name => `${name} negotiates with ${pickRandom(postApocEnemies)} for safe passage and loot.`,
            name => `${name} finds a hidden stash of ${pickRandom(postApocItems)} behind rubble.`,
            name => `${name} uses a ${pickRandom(postApocItems)} to unlock a sealed chamber.`,
            name => `${name} rescues a survivor who rewards them with a ${pickRandom(postApocItems)}.`,
            name => `${name} deciphers an encrypted message leading to a ${pickRandom(postApocItems)}.`,
            name => `${name} braves the ${pickRandom(postApocEvents)} to secure rare resources.`,
        ],
        loseMessages: [
            name => `${name} is double-crossed by ${pickRandom(postApocEnemies)} and loses everything.`,
            name => `${name} is caught in a trap while searching for the ${pickRandom(postApocItems)}.`,
            name => `${name} is forced to flee from ${pickRandom(postApocEnemies)} in the ${pickRandom(postApocLocations)}.`,
            name => `${name} is injured by a malfunctioning ${pickRandom(postApocItems)}.`,
            name => `${name} is lost in the ${pickRandom(postApocLocations)} during a ${pickRandom(postApocEvents)}.`,
            name => `${name} is betrayed by an ally and left behind.`,
            name => `${name} is overwhelmed by ${pickRandom(postApocEnemies)} and drops supplies.`,
            name => `${name} is exposed to toxic fumes in the ${pickRandom(postApocLocations)}.`,
            name => `${name} is caught in a collapsing tunnel and loses gear.`,
            name => `${name} is chased away by ${pickRandom(postApocEnemies)} before finding anything.`,
        ],
    },
    {
        description: () => `A ${pickRandom(postApocEvents)} disrupts the fragile peace at a ${pickRandom(postApocLocations)}.`,
        winMessages: [
            name => `${name} uses a ${pickRandom(postApocItems)} to shield from the ${pickRandom(postApocEvents)}.`,
            name => `${name} rallies survivors to defend the ${pickRandom(postApocLocations)}.`,
            name => `${name} salvages a ${pickRandom(postApocItems)} during the chaos.`,
            name => `${name} outsmarts ${pickRandom(postApocEnemies)} and escapes unharmed.`,
            name => `${name} finds a shortcut through the ${pickRandom(postApocLocations)}.`,
            name => `${name} repairs a broken ${pickRandom(postApocItems)} just in time.`,
            name => `${name} discovers a safe haven in the ${pickRandom(postApocLocations)}.`,
            name => `${name} disables a trap set by ${pickRandom(postApocEnemies)}.`,
            name => `${name} finds a working radio and calls for help.`,
            name => `${name} uses quick thinking to avoid disaster during the ${pickRandom(postApocEvents)}.`,
        ],
        loseMessages: [
            name => `${name} is caught off guard by the ${pickRandom(postApocEvents)}.`,
            name => `${name} is separated from the group in the ${pickRandom(postApocLocations)}.`,
            name => `${name} is injured by flying debris during the ${pickRandom(postApocEvents)}.`,
            name => `${name} loses a ${pickRandom(postApocItems)} in the confusion.`,
            name => `${name} is cornered by ${pickRandom(postApocEnemies)} and forced to surrender.`,
            name => `${name} is trapped by a collapsing structure in the ${pickRandom(postApocLocations)}.`,
            name => `${name} is exposed to radiation during the ${pickRandom(postApocEvents)}.`,
            name => `${name} is ambushed while seeking shelter.`,
            name => `${name} is forced to abandon supplies to escape.`,
            name => `${name} is knocked unconscious and wakes up with nothing.`,
        ],
    },
    {
        description: () => `A mysterious signal from the ${pickRandom(postApocLocations)} promises hope—or danger.`,
        winMessages: [
            name => `${name} traces the signal to a cache of ${pickRandom(postApocItems)}.`,
            name => `${name} deciphers the code and unlocks a hidden vault.`,
            name => `${name} teams up with survivors to secure the ${pickRandom(postApocItems)}.`,
            name => `${name} disables a security system guarding the ${pickRandom(postApocItems)}.`,
            name => `${name} outsmarts a group of ${pickRandom(postApocEnemies)} at the last moment.`,
            name => `${name} finds a map leading to a safe zone.`,
            name => `${name} hacks a terminal to reveal the location of supplies.`,
            name => `${name} rescues a trapped survivor who shares valuable intel.`,
            name => `${name} uses a ${pickRandom(postApocItems)} to bypass a locked door.`,
            name => `${name} broadcasts a message and receives a supply drop.`,
        ],
        loseMessages: [
            name => `${name} is lured into a trap by a false signal.`,
            name => `${name} is intercepted by ${pickRandom(postApocEnemies)} en route to the source.`,
            name => `${name} is caught in a malfunctioning security system.`,
            name => `${name} is forced to retreat as the signal fades.`,
            name => `${name} is ambushed by raiders at the signal's origin.`,
            name => `${name} is injured while exploring the ${pickRandom(postApocLocations)}.`,
            name => `${name} is exposed to a ${pickRandom(postApocEvents)} and loses gear.`,
            name => `${name} is betrayed by a supposed ally.`,
            name => `${name} is chased away by mutant creatures.`,
            name => `${name} is left empty-handed as the vault self-destructs.`,
        ],
    },
];
