import { Adventure } from "./index";
import { pickRandom } from "../utils/misc";

const westItems = [
    "gold nugget",
    "silver horseshoe",
    "lucky coin",
    "bandit's mask",
    "sheriff's badge",
    "old revolver",
    "cowboy hat",
    "wanted poster",
    "spurred boots",
    "whiskey flask",
];
const westEnemies = [
    "outlaw gang",
    "rattlesnake",
    "bandit leader",
    "coyote pack",
    "corrupt sheriff",
    "card shark",
    "stampeding herd",
    "bounty hunter",
    "desperado",
    "cheating gambler",
];
const westLocations = [
    "dusty saloon",
    "abandoned mine",
    "frontier town",
    "cattle ranch",
    "desert canyon",
    "railroad camp",
    "river crossing",
    "old fort",
    "prairie homestead",
    "stagecoach trail",
];
const westEvents = [
    "high noon duel",
    "bank robbery",
    "train heist",
    "barroom brawl",
    "gold rush",
    "stampede",
    "sandstorm",
    "poker game",
    "shootout",
    "snakebite incident",
];
export const westAdventures: Adventure[] = [
    {
        description: () => `A ${pickRandom(westEvents)} shakes up the ${pickRandom(westLocations)}, fortune favors the bold.`,
        winMessages: [
            name => `${name} wins a duel and claims a ${pickRandom(westItems)}.`,
            name => `${name} outsmarts the ${pickRandom(westEnemies)} and finds a hidden stash.`,
            name => `${name} strikes gold in the ${pickRandom(westLocations)}.`,
            name => `${name} discovers a map to a secret ${pickRandom(westLocations)}.`,
            name => `${name} befriends a ${pickRandom(westEnemies)} and gains valuable info.`,
            name => `${name} wins a ${pickRandom(westEvents)} and earns respect in town.`,
            name => `${name} finds a lost ${pickRandom(westItems)} near the ${pickRandom(westLocations)}.`,
            name => `${name} helps a stranger during a ${pickRandom(westEvents)} and is rewarded.`,
            name => `${name} escapes a ${pickRandom(westEnemies)} with a bag of ${pickRandom(westItems)}.`,
            name => `${name} wins big at a ${pickRandom(westEvents)} in the ${pickRandom(westLocations)}.`,
        ],
        loseMessages: [
            name => `${name} is ambushed by the ${pickRandom(westEnemies)} and loses their loot.`,
            name => `${name} is caught in a ${pickRandom(westEvents)} and must retreat.`,
            name => `${name} is injured in the ${pickRandom(westLocations)}.`,
            name => `${name} is tricked by a ${pickRandom(westEnemies)} and loses a ${pickRandom(westItems)}.`,
            name => `${name} gets lost in the ${pickRandom(westLocations)} during a ${pickRandom(westEvents)}.`,
            name => `${name} is robbed by a ${pickRandom(westEnemies)} at the ${pickRandom(westLocations)}.`,
            name => `${name} loses a bet in a ${pickRandom(westEvents)} and forfeits a ${pickRandom(westItems)}.`,
            name => `${name} is thrown out of the ${pickRandom(westLocations)} after a ${pickRandom(westEvents)}.`,
            name => `${name} is bitten by a ${pickRandom(westEnemies)} and needs to recover.`,
            name => `${name} is caught cheating in a ${pickRandom(westEvents)} and is fined.`,
        ],
    },
    {
        description: () => `Rumors of a hidden treasure spread through the ${pickRandom(westLocations)}.`,
        winMessages: [
            name => `${name} finds a ${pickRandom(westItems)} buried under the ${pickRandom(westLocations)}.`,
            name => `${name} teams up with a ${pickRandom(westEnemies)} and uncovers riches.`,
            name => `${name} solves the riddle of the ${pickRandom(westLocations)} and finds gold.`,
            name => `${name} braves a ${pickRandom(westEvents)} and comes out richer.`,
            name => `${name} discovers a forgotten stash in the ${pickRandom(westLocations)}.`,
            name => `${name} wins a ${pickRandom(westItems)} in a heated ${pickRandom(westEvents)}.`,
            name => `${name} outdraws a ${pickRandom(westEnemies)} and claims their loot.`,
            name => `${name} finds a map to a ${pickRandom(westItems)} during a ${pickRandom(westEvents)}.`,
            name => `${name} is gifted a ${pickRandom(westItems)} by a grateful stranger.`,
            name => `${name} escapes a ${pickRandom(westEnemies)} with a sack of gold.`,
        ],
        loseMessages: [
            name => `${name} is double-crossed by a ${pickRandom(westEnemies)} and loses everything.`,
            name => `${name} is caught in a ${pickRandom(westEvents)} and drops their loot.`,
            name => `${name} is chased out of the ${pickRandom(westLocations)} by angry locals.`,
            name => `${name} is swindled in a ${pickRandom(westEvents)} and loses a ${pickRandom(westItems)}.`,
            name => `${name} is trapped in the ${pickRandom(westLocations)} during a ${pickRandom(westEvents)}.`,
            name => `${name} is bitten by a ${pickRandom(westEnemies)} and loses time and gold.`,
            name => `${name} is caught snooping around the ${pickRandom(westLocations)} and is fined.`,
            name => `${name} is robbed by a masked ${pickRandom(westEnemies)}.`,
            name => `${name} loses a ${pickRandom(westItems)} in a crooked ${pickRandom(westEvents)}.`,
            name => `${name} is forced to flee the ${pickRandom(westLocations)} empty-handed.`,
        ],
    },
    {
        description: () => `A mysterious stranger arrives at the ${pickRandom(westLocations)}, stirring up trouble.`,
        winMessages: [
            name => `${name} impresses the stranger and receives a ${pickRandom(westItems)}.`,
            name => `${name} wins a secret from the stranger during a ${pickRandom(westEvents)}.`,
            name => `${name} helps the stranger and is rewarded with gold.`,
            name => `${name} uncovers the stranger's identity and gains a ${pickRandom(westItems)}.`,
            name => `${name} teams up with the stranger to defeat a ${pickRandom(westEnemies)}.`,
            name => `${name} wins a high-stakes ${pickRandom(westEvents)} against the stranger.`,
            name => `${name} is gifted a rare ${pickRandom(westItems)} by the stranger.`,
            name => `${name} learns a valuable skill from the stranger at the ${pickRandom(westLocations)}.`,
            name => `${name} and the stranger find a hidden stash in the ${pickRandom(westLocations)}.`,
            name => `${name} outsmarts the stranger in a ${pickRandom(westEvents)} and wins big.`,
        ],
        loseMessages: [
            name => `${name} is outwitted by the stranger and loses a ${pickRandom(westItems)}.`,
            name => `${name} is tricked by the stranger during a ${pickRandom(westEvents)}.`,
            name => `${name} is caught in the crossfire between the stranger and a ${pickRandom(westEnemies)}.`,
            name => `${name} loses a bet to the stranger in the ${pickRandom(westLocations)}.`,
            name => `${name} is robbed by the stranger and left in the ${pickRandom(westLocations)}.`,
            name => `${name} is forced to hand over a ${pickRandom(westItems)} to the stranger.`,
            name => `${name} is embarrassed in a ${pickRandom(westEvents)} by the stranger.`,
            name => `${name} is left behind by the stranger during a ${pickRandom(westEvents)}.`,
            name => `${name} is tricked into a trap by the stranger and a ${pickRandom(westEnemies)}.`,
            name => `${name} is outdrawn by the stranger and loses their loot.`,
        ],
    },
    {
        description: () => `A fierce ${pickRandom(westEnemies)} threatens the peace at the ${pickRandom(westLocations)}.`,
        winMessages: [
            name => `${name} defeats the ${pickRandom(westEnemies)} and is hailed as a hero.`,
            name => `${name} negotiates peace with the ${pickRandom(westEnemies)} and earns a reward.`,
            name => `${name} sets a clever trap for the ${pickRandom(westEnemies)} and wins gold.`,
            name => `${name} outsmarts the ${pickRandom(westEnemies)} during a ${pickRandom(westEvents)}.`,
            name => `${name} rescues townsfolk from the ${pickRandom(westEnemies)} and is gifted a ${pickRandom(westItems)}.`,
            name => `${name} wins a showdown with the ${pickRandom(westEnemies)} at the ${pickRandom(westLocations)}.`,
            name => `${name} finds a ${pickRandom(westItems)} left behind by the fleeing ${pickRandom(westEnemies)}.`,
            name => `${name} earns the respect of the ${pickRandom(westLocations)} after defeating the ${pickRandom(westEnemies)}.`,
            name => `${name} outguns the ${pickRandom(westEnemies)} in a ${pickRandom(westEvents)}.`,
            name => `${name} is celebrated at the ${pickRandom(westLocations)} for bravery against the ${pickRandom(westEnemies)}.`,
        ],
        loseMessages: [
            name => `${name} is overpowered by the ${pickRandom(westEnemies)} and loses a ${pickRandom(westItems)}.`,
            name => `${name} is forced to flee the ${pickRandom(westLocations)} after a defeat.`,
            name => `${name} is injured by the ${pickRandom(westEnemies)} during a ${pickRandom(westEvents)}.`,
            name => `${name} is captured by the ${pickRandom(westEnemies)} and loses their loot.`,
            name => `${name} is outsmarted by the ${pickRandom(westEnemies)} in a ${pickRandom(westEvents)}.`,
            name => `${name} is robbed by the ${pickRandom(westEnemies)} at the ${pickRandom(westLocations)}.`,
            name => `${name} is left stranded in the ${pickRandom(westLocations)} after a ${pickRandom(westEvents)}.`,
            name => `${name} is tricked by the ${pickRandom(westEnemies)} and loses a ${pickRandom(westItems)}.`,
            name => `${name} is chased out of the ${pickRandom(westLocations)} by the ${pickRandom(westEnemies)}.`,
            name => `${name} is caught in a trap set by the ${pickRandom(westEnemies)} and loses gold.`,
        ],
    },
];
