export const enum EmoteCategory {
    DUEL_CREATE = "DUEL_CREATE",
    PAUSE = "PAUSE",
    DUEL_DENY = "DUEL_DENY",
    CONGRATULATIONS = "CONGRATULATIONS",
    CONGRATULATIONS_TRASH_FISH_DEX = "CONGRATULATIONS_TRASH_FISH_DEX",
    DUEL_WIN = "DUEL_WIN",
    FACTS = "FACTS",
    QUOTES = "QUOTES",
    SAD = "SAD",
    ADVENTURE_COOLDOWN = "ADVENTURE_COOLDOWN",
    FISH_COOLDOWN = "FISH_COOLDOWN",
    FISH_FINE = "FISH_FINE",
    MUSHY = "MUSHY",
    SOCKO = "SOCKO",
    APRIL_FOOZE = "APRIL_FOOZE",
    FUSLIE = "FUSLIE",
    FUKURA = "FUKURA",
    FROG = "FROG",
    BLOBFISH = "BLOBFISH",
    SURGEONFISH = "SURGEONFISH",
    VALUE = "VALUE",
    EVENT_STARTED = "EVENT_STARTED",
    ADVENTURE_START_EMOTES = "ADVENTURE_START_EMOTES",
    ADVENTURE_END_EMOTES = "ADVENTURE_END_EMOTES",
}

export type EmoteProvider = "native" | "bttv" | "ffz" | "7tv";

// Define all unique emotes with their providers (single source of truth)
export const EMOTE_DEFINITIONS = {
    PauseChamp: { name: "PauseChamp", provider: "7tv" },
    PAUSE: { name: "PAUSE", provider: "7tv" },
    Scared: { name: "Scared", provider: "7tv" },
    NoThanks: { name: "NoThanks", provider: "7tv" },
    nope: { name: "nope", provider: "7tv" },
    Awkward: { name: "Awkward", provider: "7tv" },
    Peace: { name: "Peace", provider: "7tv" },
    EZ: { name: "EZ", provider: "7tv" },
    Pog: { name: "Pog", provider: "7tv" },
    NERD: { name: "NERD", provider: "7tv" },
    Life: { name: "Life", provider: "7tv" },
    Gaze: { name: "Gaze", provider: "7tv" },
    Sigh: { name: "Sigh", provider: "7tv" },
    smile: { name: "smile", provider: "7tv" },
    ":33": { name: ":33", provider: "7tv" },
    xd: { name: "xd", provider: "7tv" },
    Stare: { name: "Stare", provider: "7tv" },
    Waiting: { name: "Waiting", provider: "7tv" },
    FROG: { name: "FROG", provider: "7tv" },
    gg: { name: "gg", provider: "7tv" },
    GAMBA: { name: "GAMBA", provider: "7tv" },
    PauseCat: { name: "PauseCat", provider: "7tv" },
    DRAMA: { name: "DRAMA", provider: "7tv" },
    NAILS: { name: "NAILS", provider: "7tv" },
    monkaS: { name: "monkaS", provider: "7tv" },
    MONKA: { name: "MONKA", provider: "7tv" },
    SAVED: { name: "SAVED", provider: "7tv" },
    NOPERS: { name: "NOPERS", provider: "7tv" },
    oopsie: { name: "oopsie", provider: "7tv" },
    Ermm: { name: "Ermm", provider: "7tv" },
    Erm: { name: "Erm", provider: "7tv" },
    NoNo: { name: "NoNo", provider: "7tv" },
    Clap: { name: "Clap", provider: "7tv" },
    peepoClap: { name: "peepoClap", provider: "7tv" },
    catClap: { name: "catClap", provider: "7tv" },
    WW: { name: "WW", provider: "7tv" },
    pogg: { name: "pogg", provider: "7tv" },
    poggSpin: { name: "poggSpin", provider: "7tv" },
    POGGERS: { name: "POGGERS", provider: "7tv" },
    POGGIES: { name: "POGGIES", provider: "7tv" },
    HOLY: { name: "HOLY", provider: "7tv" },
    OOOO: { name: "OOOO", provider: "7tv" },
    MUGA: { name: "MUGA", provider: "7tv" },
    Cereal: { name: "Cereal", provider: "7tv" },
    mhm: { name: "mhm", provider: "7tv" },
    Nerdge: { name: "Nerdge", provider: "7tv" },
    yapping: { name: "yapping", provider: "7tv" },
    YAPPP: { name: "YAPPP", provider: "7tv" },
    peepoTalk: { name: "peepoTalk", provider: "7tv" },
    CatNerd: { name: "CatNerd", provider: "7tv" },
    PepoG: { name: "PepoG", provider: "7tv" },
    Sadge: { name: "Sadge", provider: "7tv" },
    SAJ: { name: "SAJ", provider: "7tv" },
    PepeHands: { name: "PepeHands", provider: "7tv" },
    imNOTcrying: { name: "imNOTcrying", provider: "7tv" },
    widepeepoSad: { name: "widepeepoSad", provider: "7tv" },
    Sadding: { name: "Sadding", provider: "7tv" },
    waaa: { name: "waaa", provider: "7tv" },
    BLUBBERS: { name: "BLUBBERS", provider: "7tv" },
    Pointless: { name: "Pointless", provider: "7tv" },
    CAUGHT: { name: "CAUGHT", provider: "7tv" },
    Crode: { name: "Crode", provider: "7tv" },
    OOP: { name: "OOP", provider: "7tv" },
    OuttaPocket: { name: "OuttaPocket", provider: "7tv" },
    um: { name: "um", provider: "7tv" },
    UHM: { name: "UHM", provider: "7tv" },
    LL: { name: "LL", provider: "7tv" },
    BLUBBERSWTF: { name: "BLUBBERSWTF", provider: "7tv" },
    peepoSitMad: { name: "peepoSitMad", provider: "7tv" },
    WAJAJA: { name: "WAJAJA", provider: "7tv" },
    catWait: { name: "catWait", provider: "7tv" },
    Igotmyeyesonyou: { name: "Igotmyeyesonyou", provider: "7tv" },
    aga: { name: "aga", provider: "7tv" },
    waga: { name: "waga", provider: "7tv" },
    ok: { name: "ok", provider: "7tv" },
    Gregory: { name: "Gregory", provider: "7tv" },
    peepoHappyWaiting: { name: "peepoHappyWaiting", provider: "7tv" },
    stara: { name: "stara", provider: "7tv" },
    staree: { name: "staree", provider: "7tv" },
    bla: { name: "bla", provider: "7tv" },
    ogo: { name: "ogo", provider: "7tv" },
    peepoSit: { name: "peepoSit", provider: "7tv" },
    PepeDadBod: { name: "PepeDadBod", provider: "7tv" },
    peepoCute: { name: "peepoCute", provider: "7tv" },
    FurretWalk: { name: "FurretWalk", provider: "7tv" },
    wooperJam: { name: "wooperJam", provider: "7tv" },
    frogJam: { name: "frogJam", provider: "7tv" },
    YIPPIE: { name: "YIPPIE", provider: "7tv" },
    NowWot: { name: "NowWot", provider: "7tv" },
    PausersHype: { name: "PausersHype", provider: "7tv" },
    agaCute: { name: "agaCute", provider: "7tv" },
    cuteSit: { name: "cuteSit", provider: "7tv" },
    cuteSitFriendship: { name: "cuteSitFriendship", provider: "7tv" },
    clappi: { name: "clappi", provider: "7tv" },
    mushyJam: { name: "mushyJam", provider: "7tv" },
    mushyOk: { name: "mushyOk", provider: "7tv" },
    mushySit: { name: "mushySit", provider: "7tv" },
    mushyWheel: { name: "mushyWheel", provider: "7tv" },
    shocko: { name: "shocko", provider: "7tv" },
    wideSock: { name: "wideSock", provider: "7tv" },
    sockTime: { name: "sockTime", provider: "7tv" },
    sockZZZ: { name: "sockZZZ", provider: "7tv" },
    sockBday: { name: "sockBday", provider: "7tv" },
    sockSludge: { name: "sockSludge", provider: "7tv" },
    fusSock: { name: "fusSock", provider: "native" },
    fusApril: { name: "fusApril", provider: "native" },
    fusMoney: { name: "fusMoney", provider: "native" },
    fusVlog: { name: "fusVlog", provider: "native" },
    fusDory: { name: "fusDory", provider: "native" },
    fus7: { name: "fus7", provider: "native" },
    fusW: { name: "fusW", provider: "native" },
    fusNotes: { name: "fusNotes", provider: "7tv" },
    fusG: { name: "fusG", provider: "native" },
    fusBald: { name: "fusBald", provider: "7tv" },
    fusFarm: { name: "fusFarm", provider: "7tv" },
    fusLurks: { name: "fusLurks", provider: "7tv" },
    FishMoley: { name: "FishMoley", provider: "7tv" },
    fusJR: { name: "fusJR", provider: "7tv" },
    WOWMOM: { name: "WOWMOM", provider: "7tv" },
    Alarm: { name: "Alarm", provider: "7tv" },
    dinkDonk: { name: "dinkDonk", provider: "7tv" },
    kuraPeek: { name: "kuraPeek", provider: "7tv" },
    NatePOG: { name: "NatePOG", provider: "7tv" },
    CLIPSS: { name: "CLIPSS", provider: "7tv" },
} as const;

export type EmoteName = keyof typeof EMOTE_DEFINITIONS;

export interface Emote {
    name: EmoteName;
    provider: EmoteProvider;
}

export type EmoteBundle<T extends readonly EmoteName[]> = { [K in keyof T]: T[K] extends EmoteName ? (typeof EMOTE_DEFINITIONS)[T[K]] : never };

// Create Emote objects from definitions
export function Emote<T extends EmoteName>(name: T): (typeof EMOTE_DEFINITIONS)[T] {
    return EMOTE_DEFINITIONS[name];
}

export function EmoteBundle<const T extends readonly EmoteName[]>(...names: T): EmoteBundle<T> {
    return names.map(n => Emote(n)) as EmoteBundle<T>;
}

export function Emotes<const T extends readonly EmoteName[]>(...names: T): { [K in T[number]]: (typeof EMOTE_DEFINITIONS)[K] } {
    return Object.fromEntries(names.map(n => [n, Emote(n)])) as { [K in T[number]]: (typeof EMOTE_DEFINITIONS)[K] };
}

export const CATEGORY_EMOTES_RECORD = {
    [EmoteCategory.ADVENTURE_END_EMOTES]: Emotes("dinkDonk", "Alarm"),
    [EmoteCategory.ADVENTURE_START_EMOTES]: Emotes("GAMBA"),
    [EmoteCategory.DUEL_CREATE]: Emotes("GAMBA", "PauseChamp", "PAUSE", "PauseCat", "PausersHype", "DRAMA", "NAILS"),
    [EmoteCategory.PAUSE]: Emotes("PauseChamp", "PAUSE", "PauseCat", "PausersHype"),
    [EmoteCategory.DUEL_DENY]: Emotes(
        "Scared",
        "monkaS",
        "MONKA",
        "NoThanks",
        "SAVED",
        "NOPERS",
        "nope",
        "Awkward",
        "Peace",
        "oopsie",
        "Ermm",
        "Erm",
        "NoNo",
    ),
    [EmoteCategory.CONGRATULATIONS]: { EZ_Clap: EmoteBundle("EZ", "Clap"), ...Emotes("peepoClap", "clappi", "catClap", "Pog") },
    [EmoteCategory.CONGRATULATIONS_TRASH_FISH_DEX]: Emotes("peepoClap", "clappi", "catClap", "Pog", "WW"),
    [EmoteCategory.DUEL_WIN]: {
        EZ_Clap: EmoteBundle("EZ", "Clap"),
        ...Emotes("EZ", "Pog", "pogg", "poggSpin", "POGGERS", "POGGIES", "WW", "HOLY", "OOOO", "MUGA", "Cereal", "gg"),
    },
    [EmoteCategory.FACTS]: Emotes("fusNotes", "NERD", "mhm", "Nerdge", "yapping", "YAPPP", "fusG", "peepoTalk", "CatNerd", "PepoG"),
    [EmoteCategory.QUOTES]: Emotes("fusNotes", "NERD", "mhm", "Nerdge", "yapping", "YAPPP", "fusG", "peepoTalk", "CatNerd", "PepoG", "Life", "Gaze"),
    [EmoteCategory.SAD]: Emotes("Sadge", "SAJ", "PepeHands", "imNOTcrying", "widepeepoSad", "Sadding", "Sigh", "waaa", "BLUBBERS", "Pointless"),
    [EmoteCategory.ADVENTURE_COOLDOWN]: Emotes(
        "Waiting",
        "catWait",
        "Stare",
        "Gaze",
        "Igotmyeyesonyou",
        "aga",
        "waga",
        "ok",
        "Life",
        "agaCute",
        "Gregory",
        "smile",
        ":33",
        "peepoHappyWaiting",
        "stara",
        "staree",
        "bla",
        "NowWot",
        "ogo",
        "peepoSit",
        "PepeDadBod",
        "cuteSit",
        "peepoCute",
        "cuteSitFriendship",
        "xd",
        "FurretWalk",
        "wooperJam",
    ),
    [EmoteCategory.FISH_COOLDOWN]: Emotes(
        "Waiting",
        "catWait",
        "Stare",
        "Gaze",
        "Igotmyeyesonyou",
        "aga",
        "waga",
        "ok",
        "Life",
        "agaCute",
        "Gregory",
        "smile",
        ":33",
        "peepoHappyWaiting",
        "stara",
        "staree",
        "bla",
        "NowWot",
        "ogo",
        "peepoSit",
        "PepeDadBod",
        "cuteSit",
        "peepoCute",
        "cuteSitFriendship",
        "xd",
        "FurretWalk",
        "wooperJam",
    ),
    [EmoteCategory.FISH_FINE]: Emotes(
        "Sadge",
        "SAJ",
        "CAUGHT",
        "PepeHands",
        "Crode",
        "imNOTcrying",
        "OOP",
        "oopsie",
        "OuttaPocket",
        "Sadding",
        "um",
        "widepeepoSad",
        "UHM",
        "LL",
        "BLUBBERS",
        "BLUBBERSWTF",
        "Sigh",
        "peepoSitMad",
        "Pointless",
        "waaa",
        "WAJAJA",
    ),
    [EmoteCategory.MUSHY]: Emotes("mushyJam", "mushyOk", "mushySit", "mushyWheel"),
    [EmoteCategory.SOCKO]: Emotes("shocko", "wideSock", "sockTime", "sockZZZ", "sockBday", "sockSludge", "fusSock"),
    [EmoteCategory.APRIL_FOOZE]: Emotes("fusApril", "fusMoney", "fusVlog"),
    [EmoteCategory.FUSLIE]: Emotes("fus7", "fusW", "fusBald", "fusFarm", "fusLurks", "WOWMOM", "fusJR"),
    [EmoteCategory.FROG]: Emotes("FROG", "Pog", "frogJam"),
    [EmoteCategory.BLOBFISH]: Emotes("FishMoley"),
    [EmoteCategory.SURGEONFISH]: Emotes("fusDory"),
    [EmoteCategory.VALUE]: Emotes("WAJAJA", "pogg", "poggSpin", "YIPPIE", "POGGIES", "POGGERS", "Pog", "HOLY", "Cereal", "MUGA", "OOOO"),
    [EmoteCategory.EVENT_STARTED]: Emotes("pogg", "YIPPIE", "POGGIES", "POGGERS", "Pog", "Cereal", "OOOO"),
    [EmoteCategory.FUKURA]: Emotes("NatePOG", "kuraPeek", "CLIPSS"),
} as const;

type CategoryEmotesArray = { [key in keyof typeof CATEGORY_EMOTES_RECORD]: (Emote | Emote[])[] };

// Derive array version from record to avoid duplication
export const CATEGORY_EMOTES: CategoryEmotesArray = Object.entries(CATEGORY_EMOTES_RECORD).reduce(
    (acc, [category, emotes]) => ({ ...acc, [category]: Object.values(emotes || {}) }),
    {} as CategoryEmotesArray,
);