export enum EmoteCategory {
    DUEL_CREATE = "DUEL_CREATE",
    PAUSE = "PAUSE",
    DUEL_DENY = "DUEL_DENY",
    CONGRATULATIONS = "CONGRATULATIONS",
    CONGRATULATIONS_TRASH_FISH_DEX = "CONGRATULATIONS_TRASH_FISH_DEX",
    DUEL_WIN = "DUEL_WIN",
    FACTS = "FACTS",
    QUOTES = "QUOTES",
    SAD = "SAD",
    ADVENTURE_COOLDOWN = "ADVENTURE_COOLDOWN",
    FISH_COOLDOWN = "FISH_COOLDOWN",
    FISH_FINE = "FISH_FINE",
    MUSHY = "MUSHY",
    SOCKO = "SOCKO",
    APRIL_FOOZE = "APRIL_FOOZE",
    FUSLIE = "FUSLIE",
    FROG = "FROG",
    BLOBFISH = "BLOBFISH",
    SURGEONFISH = "SURGEONFISH",
    VALUE = "VALUE",
    EVENT_STARTED = "EVENT_STARTED",
    ADVENTURE_START_EMOTES = "ADVENTURE_START_EMOTES",
    ADVENTURE_END_EMOTES = "ADVENTURE_END_EMOTES",
}

export type EmoteProvider = "native" | "bttv" | "ffz" | "7tv";

// Define all unique emotes with their providers (single source of truth)
export const EMOTE_DEFINITIONS = {
    PauseChamp: "7tv",
    PAUSE: "7tv",
    Scared: "7tv",
    NoThanks: "7tv",
    nope: "7tv",
    Awkward: "7tv",
    Peace: "7tv",
    EZ: "7tv",
    Pog: "7tv",
    NERD: "7tv",
    Life: "7tv",
    Gaze: "7tv",
    Sigh: "7tv",
    smile: "7tv",
    ":33": "7tv",
    xd: "7tv",
    Stare: "7tv",
    Waiting: "7tv",
    FROG: "7tv",
    gg: "7tv",
    GAMBA: "7tv",
    PauseCat: "7tv",
    DRAMA: "7tv",
    NAILS: "7tv",
    monkaS: "7tv",
    MONKA: "7tv",
    SAVED: "7tv",
    NOPERS: "7tv",
    oopsie: "7tv",
    Ermm: "7tv",
    Erm: "7tv",
    NoNo: "7tv",
    "EZ Clap": "7tv",
    peepoClap: "7tv",
    catClap: "7tv",
    WW: "7tv",
    pogg: "7tv",
    poggSpin: "7tv",
    POGGERS: "7tv",
    POGGIES: "7tv",
    HOLY: "7tv",
    OOOO: "7tv",
    MUGA: "7tv",
    Cereal: "7tv",
    mhm: "7tv",
    Nerdge: "7tv",
    yapping: "7tv",
    YAPPP: "7tv",
    peepoTalk: "7tv",
    CatNerd: "7tv",
    PepoG: "7tv",
    Sadge: "7tv",
    SAJ: "7tv",
    PepeHands: "7tv",
    imNOTcrying: "7tv",
    widepeepoSad: "7tv",
    Sadding: "7tv",
    waaa: "7tv",
    BLUBBERS: "7tv",
    Pointless: "7tv",
    CAUGHT: "7tv",
    Crode: "7tv",
    OOP: "7tv",
    OuttaPocket: "7tv",
    um: "7tv",
    UHM: "7tv",
    LL: "7tv",
    BLUBBERSWTF: "7tv",
    peepoSitMad: "7tv",
    WAJAJA: "7tv",
    catWait: "7tv",
    Igotmyeyesonyou: "7tv",
    aga: "7tv",
    waga: "7tv",
    ok: "7tv",
    Gregory: "7tv",
    peepoHappyWaiting: "7tv",
    stara: "7tv",
    staree: "7tv",
    bla: "7tv",
    ogo: "7tv",
    peepoSit: "7tv",
    PepeDadBod: "7tv",
    peepoCute: "7tv",
    FurretWalk: "7tv",
    wooperJam: "7tv",
    frogJam: "7tv",
    YIPPIE: "7tv",
    NowWot: "7tv",
    PausersHype: "7tv",
    agaCute: "7tv",
    cuteSit: "7tv",
    cuteSitFriendship: "7tv",
    clappi: "7tv",
    mushyJam: "7tv",
    mushyOk: "7tv",
    mushySit: "7tv",
    mushyWheel: "7tv",
    shocko: "7tv",
    wideSock: "7tv",
    sockTime: "7tv",
    sockZZZ: "7tv",
    sockBday: "7tv",
    sockSludge: "7tv",
    fusSock: "7tv",
    fusApril: "native",
    fusMoney: "native",
    fusVlog: "native",
    fusDory: "native",
    fus7: "native",
    fusW: "native",
    fusNotes: "native",
    fusG: "native",
    fusBald: "7tv",
    fusFarm: "7tv",
    fusLurks: "7tv",
    FishMoley: "7tv",
    fusJR: "7tv",
    WOWMOM: "7tv",
    Alert: "7tv",
    dinkDonk: "7tv",
} as const;

export type EmoteName = keyof typeof EMOTE_DEFINITIONS;

export interface Emote {
    name: EmoteName;
    provider: EmoteProvider;
}
// Create Emote objects from definitions
export function Emote(name: EmoteName) {
    const provider = EMOTE_DEFINITIONS[name];
    if (!provider) {
        throw new Error(`Emote not found in definitions: ${name}`);
    }
    return { name, provider };
}

type CategoryEmotesArray = { [key in EmoteCategory]: Emote[] };

export const CATEGORY_EMOTES_RECORD = {
    [EmoteCategory.ADVENTURE_END_EMOTES]: { dinkDonk: Emote("dinkDonk"), Alert: Emote("Alert") },
    [EmoteCategory.ADVENTURE_START_EMOTES]: { GAMBA: Emote("GAMBA") },
    [EmoteCategory.DUEL_CREATE]: {
        GAMBA: Emote("GAMBA"),
        PauseChamp: Emote("PauseChamp"),
        PAUSE: Emote("PAUSE"),
        PauseCat: Emote("PauseCat"),
        PausersHype: Emote("PausersHype"),
        DRAMA: Emote("DRAMA"),
        NAILS: Emote("NAILS"),
    },
    [EmoteCategory.PAUSE]: { PauseChamp: Emote("PauseChamp"), PAUSE: Emote("PAUSE"), PauseCat: Emote("PauseCat"), PausersHype: Emote("PausersHype") },
    [EmoteCategory.DUEL_DENY]: {
        Scared: Emote("Scared"),
        monkaS: Emote("monkaS"),
        MONKA: Emote("MONKA"),
        NoThanks: Emote("NoThanks"),
        SAVED: Emote("SAVED"),
        NOPERS: Emote("NOPERS"),
        nope: Emote("nope"),
        Awkward: Emote("Awkward"),
        Peace: Emote("Peace"),
        oopsie: Emote("oopsie"),
        Ermm: Emote("Ermm"),
        Erm: Emote("Erm"),
        NoNo: Emote("NoNo"),
    },
    [EmoteCategory.CONGRATULATIONS]: {
        EZ: Emote("EZ Clap"),
        peepoClap: Emote("peepoClap"),
        clappi: Emote("clappi"),
        catClap: Emote("catClap"),
        Pog: Emote("Pog"),
    },
    [EmoteCategory.CONGRATULATIONS_TRASH_FISH_DEX]: {
        peepoClap: Emote("peepoClap"),
        clappi: Emote("clappi"),
        catClap: Emote("catClap"),
        Pog: Emote("Pog"),
        WW: Emote("WW"),
    },
    [EmoteCategory.DUEL_WIN]: {
        EZ: Emote("EZ"),
        "EZ Clap": Emote("EZ Clap"),
        Pog: Emote("Pog"),
        pogg: Emote("pogg"),
        poggSpin: Emote("poggSpin"),
        POGGERS: Emote("POGGERS"),
        POGGIES: Emote("POGGIES"),
        WW: Emote("WW"),
        HOLY: Emote("HOLY"),
        OOOO: Emote("OOOO"),
        MUGA: Emote("MUGA"),
        Cereal: Emote("Cereal"),
        gg: Emote("gg"),
    },
    [EmoteCategory.FACTS]: {
        fusNotes: Emote("fusNotes"),
        NERD: Emote("NERD"),
        mhm: Emote("mhm"),
        Nerdge: Emote("Nerdge"),
        yapping: Emote("yapping"),
        YAPPP: Emote("YAPPP"),
        fusG: Emote("fusG"),
        peepoTalk: Emote("peepoTalk"),
        CatNerd: Emote("CatNerd"),
        PepoG: Emote("PepoG"),
    },
    [EmoteCategory.QUOTES]: {
        fusNotes: Emote("fusNotes"),
        NERD: Emote("NERD"),
        mhm: Emote("mhm"),
        Nerdge: Emote("Nerdge"),
        yapping: Emote("yapping"),
        YAPPP: Emote("YAPPP"),
        fusG: Emote("fusG"),
        peepoTalk: Emote("peepoTalk"),
        CatNerd: Emote("CatNerd"),
        PepoG: Emote("PepoG"),
        Life: Emote("Life"),
        Gaze: Emote("Gaze"),
    },
    [EmoteCategory.SAD]: {
        Sadge: Emote("Sadge"),
        SAJ: Emote("SAJ"),
        PepeHands: Emote("PepeHands"),
        imNOTcrying: Emote("imNOTcrying"),
        widepeepoSad: Emote("widepeepoSad"),
        Sadding: Emote("Sadding"),
        Sigh: Emote("Sigh"),
        waaa: Emote("waaa"),
        BLUBBERS: Emote("BLUBBERS"),
        Pointless: Emote("Pointless"),
    },
    [EmoteCategory.ADVENTURE_COOLDOWN]: {
        Waiting: Emote("Waiting"),
        catWait: Emote("catWait"),
        Stare: Emote("Stare"),
        Gaze: Emote("Gaze"),
        Igotmyeyesonyou: Emote("Igotmyeyesonyou"),
        aga: Emote("aga"),
        waga: Emote("waga"),
        ok: Emote("ok"),
        Life: Emote("Life"),
        agaCute: Emote("agaCute"),
        Gregory: Emote("Gregory"),
        smile: Emote("smile"),
        ":33": Emote(":33"),
        peepoHappyWaiting: Emote("peepoHappyWaiting"),
        stara: Emote("stara"),
        staree: Emote("staree"),
        bla: Emote("bla"),
        NowWot: Emote("NowWot"),
        ogo: Emote("ogo"),
        peepoSit: Emote("peepoSit"),
        PepeDadBod: Emote("PepeDadBod"),
        cuteSit: Emote("cuteSit"),
        peepoCute: Emote("peepoCute"),
        cuteSitFriendship: Emote("cuteSitFriendship"),
        xd: Emote("xd"),
        FurretWalk: Emote("FurretWalk"),
        wooperJam: Emote("wooperJam"),
    },
    [EmoteCategory.FISH_COOLDOWN]: {
        Waiting: Emote("Waiting"),
        catWait: Emote("catWait"),
        Stare: Emote("Stare"),
        Gaze: Emote("Gaze"),
        Igotmyeyesonyou: Emote("Igotmyeyesonyou"),
        aga: Emote("aga"),
        waga: Emote("waga"),
        ok: Emote("ok"),
        Life: Emote("Life"),
        agaCute: Emote("agaCute"),
        Gregory: Emote("Gregory"),
        smile: Emote("smile"),
        ":33": Emote(":33"),
        peepoHappyWaiting: Emote("peepoHappyWaiting"),
        stara: Emote("stara"),
        staree: Emote("staree"),
        bla: Emote("bla"),
        NowWot: Emote("NowWot"),
        ogo: Emote("ogo"),
        peepoSit: Emote("peepoSit"),
        PepeDadBod: Emote("PepeDadBod"),
        cuteSit: Emote("cuteSit"),
        peepoCute: Emote("peepoCute"),
        cuteSitFriendship: Emote("cuteSitFriendship"),
        xd: Emote("xd"),
        FurretWalk: Emote("FurretWalk"),
        wooperJam: Emote("wooperJam"),
    },
    [EmoteCategory.FISH_FINE]: {
        Sadge: Emote("Sadge"),
        SAJ: Emote("SAJ"),
        CAUGHT: Emote("CAUGHT"),
        PepeHands: Emote("PepeHands"),
        Crode: Emote("Crode"),
        imNOTcrying: Emote("imNOTcrying"),
        OOP: Emote("OOP"),
        oopsie: Emote("oopsie"),
        OuttaPocket: Emote("OuttaPocket"),
        Sadding: Emote("Sadding"),
        um: Emote("um"),
        widepeepoSad: Emote("widepeepoSad"),
        UHM: Emote("UHM"),
        LL: Emote("LL"),
        BLUBBERS: Emote("BLUBBERS"),
        BLUBBERSWTF: Emote("BLUBBERSWTF"),
        Sigh: Emote("Sigh"),
        peepoSitMad: Emote("peepoSitMad"),
        Pointless: Emote("Pointless"),
        waaa: Emote("waaa"),
        WAJAJA: Emote("WAJAJA"),
    },
    [EmoteCategory.MUSHY]: { mushyJam: Emote("mushyJam"), mushyOk: Emote("mushyOk"), mushySit: Emote("mushySit"), mushyWheel: Emote("mushyWheel") },
    [EmoteCategory.SOCKO]: {
        shocko: Emote("shocko"),
        wideSock: Emote("wideSock"),
        sockTime: Emote("sockTime"),
        sockZZZ: Emote("sockZZZ"),
        sockBday: Emote("sockBday"),
        sockSludge: Emote("sockSludge"),
        fusSock: Emote("fusSock"),
    },
    [EmoteCategory.APRIL_FOOZE]: { fusApril: Emote("fusApril"), fusMoney: Emote("fusMoney"), fusVlog: Emote("fusVlog") },
    [EmoteCategory.FUSLIE]: {
        fus7: Emote("fus7"),
        fusW: Emote("fusW"),
        fusBald: Emote("fusBald"),
        fusFarm: Emote("fusFarm"),
        fusLurks: Emote("fusLurks"),
        WOWMOM: Emote("WOWMOM"),
        fusJR: Emote("fusJR"),
    },
    [EmoteCategory.FROG]: { FROG: Emote("FROG"), Pog: Emote("Pog"), frogJam: Emote("frogJam") },
    [EmoteCategory.BLOBFISH]: { FishMoley: Emote("FishMoley") },
    [EmoteCategory.SURGEONFISH]: { fusDory: Emote("fusDory") },
    [EmoteCategory.VALUE]: {
        WAJAJA: Emote("WAJAJA"),
        pogg: Emote("pogg"),
        poggSpin: Emote("poggSpin"),
        YIPPIE: Emote("YIPPIE"),
        POGGIES: Emote("POGGIES"),
        POGGERS: Emote("POGGERS"),
        Pog: Emote("Pog"),
        HOLY: Emote("HOLY"),
        Cereal: Emote("Cereal"),
        MUGA: Emote("MUGA"),
        OOOO: Emote("OOOO"),
    },
    [EmoteCategory.EVENT_STARTED]: {
        pogg: Emote("pogg"),
        YIPPIE: Emote("YIPPIE"),
        POGGIES: Emote("POGGIES"),
        POGGERS: Emote("POGGERS"),
        Pog: Emote("Pog"),
        Cereal: Emote("Cereal"),
        OOOO: Emote("OOOO"),
    },
} as const;

// Derive array version from record to avoid duplication
export const CATEGORY_EMOTES: CategoryEmotesArray = Object.entries(CATEGORY_EMOTES_RECORD).reduce(
    (acc, [category, emotes]) => ({ ...acc, [category]: Object.values(emotes || {}) }),
    {} as CategoryEmotesArray,
);
