import { AdventureCheck } from "./checks";
import { pickWeightedSeeded, SeedPart } from "./random";
import { AdventureThemeCode } from "./themes";

export const ADVENTURE_ITEM_RARITIES = ["common", "uncommon", "rare", "epic"] as const;
export type AdventureItemRarity = (typeof ADVENTURE_ITEM_RARITIES)[number];

export const ADVENTURE_ITEM_KINDS = ["equipment", "consumable", "material", "collectible"] as const;
export type AdventureItemKind = (typeof ADVENTURE_ITEM_KINDS)[number];

export const ADVENTURE_ITEM_SLOTS = ["weapon", "armor", "tool", "charm", "none"] as const;
export type AdventureItemSlot = (typeof ADVENTURE_ITEM_SLOTS)[number];

export interface AdventureItemBonus {
    readonly check: AdventureCheck;
    readonly modifier: 1;
}

export interface AdventureItemDefinition {
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly theme: AdventureThemeCode;
    readonly rarity: AdventureItemRarity;
    readonly kind: AdventureItemKind;
    readonly slot: AdventureItemSlot;
    readonly bonus: AdventureItemBonus;
}

export const LOOT_RARITY_WEIGHTS: Readonly<Record<AdventureItemRarity, number>> = { common: 65, uncommon: 25, rare: 8, epic: 2 };

export const ADVENTURE_ITEMS: readonly AdventureItemDefinition[] = [
    {
        id: "fantasy.enchanted-dagger.v1",
        name: "Enchanted Dagger",
        description: "A balanced blade that hums near danger.",
        theme: "fantasy",
        rarity: "common",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "might", modifier: 1 },
    },
    {
        id: "fantasy.ancient-rune.v1",
        name: "Ancient Rune",
        description: "A palm-sized sigil that steadies spellwork.",
        theme: "fantasy",
        rarity: "uncommon",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "arcana", modifier: 1 },
    },
    {
        id: "fantasy.elven-bow.v1",
        name: "Elven Bow",
        description: "A quiet bow made for patient hunters.",
        theme: "fantasy",
        rarity: "rare",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "stealth", modifier: 1 },
    },
    {
        id: "sci-fi.tachyon-scanner.v1",
        name: "Tachyon Scanner",
        description: "Detects faint signals before ordinary sensors react.",
        theme: "sci-fi",
        rarity: "common",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "perception", modifier: 1 },
    },
    {
        id: "sci-fi.neural-uplink.v1",
        name: "Neural Uplink",
        description: "Accelerates the interpretation of unfamiliar data.",
        theme: "sci-fi",
        rarity: "uncommon",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "knowledge", modifier: 1 },
    },
    {
        id: "sci-fi.plasma-rifle.v1",
        name: "Plasma Rifle",
        description: "A compact weapon with predictive targeting.",
        theme: "sci-fi",
        rarity: "rare",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "agility", modifier: 1 },
    },
    {
        id: "cyberpunk.hacking-deck.v1",
        name: "Hacking Deck",
        description: "A hardened console loaded with intrusion routines.",
        theme: "cyberpunk",
        rarity: "common",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "technology", modifier: 1 },
    },
    {
        id: "cyberpunk.stealth-module.v1",
        name: "Stealth Module",
        description: "Dampens heat, sound, and identifying signals.",
        theme: "cyberpunk",
        rarity: "uncommon",
        kind: "equipment",
        slot: "armor",
        bonus: { check: "stealth", modifier: 1 },
    },
    {
        id: "cyberpunk.forged-identity.v1",
        name: "Forged Identity",
        description: "A complete web of convincing digital credentials.",
        theme: "cyberpunk",
        rarity: "rare",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "deception", modifier: 1 },
    },
    {
        id: "mythological.aegis-shard.v1",
        name: "Aegis Shard",
        description: "A fragment of a legendary shield that refuses to yield.",
        theme: "mythological",
        rarity: "common",
        kind: "equipment",
        slot: "armor",
        bonus: { check: "endurance", modifier: 1 },
    },
    {
        id: "mythological.sacred-scroll.v1",
        name: "Sacred Scroll",
        description: "Records old names, prophecies, and heroic weaknesses.",
        theme: "mythological",
        rarity: "uncommon",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "knowledge", modifier: 1 },
    },
    {
        id: "mythological.blessed-amulet.v1",
        name: "Blessed Amulet",
        description: "A warm token that bolsters courage before the divine.",
        theme: "mythological",
        rarity: "rare",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "spirit", modifier: 1 },
    },
    {
        id: "post-apocalyptic.rad-suit.v1",
        name: "Rad Suit",
        description: "Patched protection against fallout and hostile weather.",
        theme: "post-apocalyptic",
        rarity: "common",
        kind: "equipment",
        slot: "armor",
        bonus: { check: "endurance", modifier: 1 },
    },
    {
        id: "post-apocalyptic.water-purifier.v1",
        name: "Water Purifier",
        description: "Turns questionable scavenged water into a safe reserve.",
        theme: "post-apocalyptic",
        rarity: "uncommon",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "survival", modifier: 1 },
    },
    {
        id: "post-apocalyptic.jury-rig-kit.v1",
        name: "Jury-Rig Kit",
        description: "A compact collection of adaptable salvage and tools.",
        theme: "post-apocalyptic",
        rarity: "rare",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "technology", modifier: 1 },
    },
    {
        id: "pirate.tideworn-compass.v1",
        name: "Tideworn Compass",
        description: "Its needle finds safe water even beneath black clouds.",
        theme: "pirate",
        rarity: "common",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "survival", modifier: 1 },
    },
    {
        id: "pirate.buccaneer-cutlass.v1",
        name: "Buccaneer Cutlass",
        description: "A light blade suited to a rolling deck.",
        theme: "pirate",
        rarity: "uncommon",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "agility", modifier: 1 },
    },
    {
        id: "pirate.captains-signet.v1",
        name: "Captain's Signet",
        description: "A respected seal that carries authority in every port.",
        theme: "pirate",
        rarity: "rare",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "presence", modifier: 1 },
    },
    {
        id: "steampunk.brass-monocle.v1",
        name: "Brass Monocle",
        description: "Magnifies hairline faults in intricate machinery.",
        theme: "steampunk",
        rarity: "common",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "perception", modifier: 1 },
    },
    {
        id: "steampunk.aether-wrench.v1",
        name: "Aether Wrench",
        description: "Tunes machinery whose workings are only partly physical.",
        theme: "steampunk",
        rarity: "uncommon",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "technology", modifier: 1 },
    },
    {
        id: "steampunk.clockwork-wings.v1",
        name: "Clockwork Wings",
        description: "Foldaway wings that make impossible leaps merely difficult.",
        theme: "steampunk",
        rarity: "rare",
        kind: "equipment",
        slot: "armor",
        bonus: { check: "agility", modifier: 1 },
    },
    {
        id: "superhero.titan-gauntlets.v1",
        name: "Titan Gauntlets",
        description: "Reinforced gloves that focus tremendous force.",
        theme: "superhero",
        rarity: "common",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "might", modifier: 1 },
    },
    {
        id: "superhero.kinetic-suit.v1",
        name: "Kinetic Suit",
        description: "Redirects momentum into precise bursts of movement.",
        theme: "superhero",
        rarity: "uncommon",
        kind: "equipment",
        slot: "armor",
        bonus: { check: "agility", modifier: 1 },
    },
    {
        id: "superhero.beacon-emblem.v1",
        name: "Beacon Emblem",
        description: "A hopeful symbol recognized across the city.",
        theme: "superhero",
        rarity: "rare",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "presence", modifier: 1 },
    },
    {
        id: "horror.silver-crucifix.v1",
        name: "Silver Crucifix",
        description: "A ward polished by generations of frightened hands.",
        theme: "horror",
        rarity: "common",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "spirit", modifier: 1 },
    },
    {
        id: "horror.occult-journal.v1",
        name: "Occult Journal",
        description: "Connects recurring symbols to the things they summon.",
        theme: "horror",
        rarity: "uncommon",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "knowledge", modifier: 1 },
    },
    {
        id: "horror.hunters-lantern.v1",
        name: "Hunter's Lantern",
        description: "Its cold flame reveals tracks that should not exist.",
        theme: "horror",
        rarity: "rare",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "perception", modifier: 1 },
    },
    {
        id: "western.quickdraw-revolver.v1",
        name: "Quickdraw Revolver",
        description: "A smooth action rewards a steady, practiced hand.",
        theme: "western",
        rarity: "common",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "agility", modifier: 1 },
    },
    {
        id: "western.sheriffs-badge.v1",
        name: "Sheriff's Badge",
        description: "A badge that can settle a room before trouble starts.",
        theme: "western",
        rarity: "uncommon",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "presence", modifier: 1 },
    },
    {
        id: "western.trail-saddlebags.v1",
        name: "Trail Saddlebags",
        description: "Keep vital supplies organized across the longest ride.",
        theme: "western",
        rarity: "rare",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "survival", modifier: 1 },
    },
    {
        id: "spy.hacking-kit.v1",
        name: "Hacking Kit",
        description: "An unmarked case of adaptable intrusion hardware.",
        theme: "spy",
        rarity: "common",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "technology", modifier: 1 },
    },
    {
        id: "spy.forged-passport.v1",
        name: "Forged Passport",
        description: "A flawless identity supported by carefully planted records.",
        theme: "spy",
        rarity: "uncommon",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "deception", modifier: 1 },
    },
    {
        id: "spy.laser-watch.v1",
        name: "Laser Watch",
        description: "An ordinary-looking watch with several quiet solutions.",
        theme: "spy",
        rarity: "rare",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "stealth", modifier: 1 },
    },
    {
        id: "egyptian.golden-scarab.v1",
        name: "Golden Scarab",
        description: "A funerary charm said to shelter the courageous.",
        theme: "egyptian",
        rarity: "common",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "spirit", modifier: 1 },
    },
    {
        id: "egyptian.papyrus-scroll.v1",
        name: "Papyrus Scroll",
        description: "A preserved record of dynasties and secret passages.",
        theme: "egyptian",
        rarity: "uncommon",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "knowledge", modifier: 1 },
    },
    {
        id: "egyptian.surveyors-ankh.v1",
        name: "Surveyor's Ankh",
        description: "Its shadow reveals subtle changes in worked stone.",
        theme: "egyptian",
        rarity: "rare",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "perception", modifier: 1 },
    },
    {
        id: "atlantis.pearl-trident.v1",
        name: "Pearl Trident",
        description: "A royal weapon that moves cleanly through crushing water.",
        theme: "atlantis",
        rarity: "common",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "might", modifier: 1 },
    },
    {
        id: "atlantis.sea-crystal.v1",
        name: "Sea Crystal",
        description: "A tranquil blue shard that quiets the abyss.",
        theme: "atlantis",
        rarity: "uncommon",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "spirit", modifier: 1 },
    },
    {
        id: "atlantis.pressure-mantle.v1",
        name: "Pressure Mantle",
        description: "Ancient fabric that braces its wearer against the depths.",
        theme: "atlantis",
        rarity: "rare",
        kind: "equipment",
        slot: "armor",
        bonus: { check: "endurance", modifier: 1 },
    },
    {
        id: "dinosaur.stone-spear.v1",
        name: "Stone Spear",
        description: "A dependable weapon for keeping enormous teeth at distance.",
        theme: "dinosaur",
        rarity: "common",
        kind: "equipment",
        slot: "weapon",
        bonus: { check: "might", modifier: 1 },
    },
    {
        id: "dinosaur.fire-starter.v1",
        name: "Fire Starter",
        description: "Produces a reliable flame even in primeval rain.",
        theme: "dinosaur",
        rarity: "uncommon",
        kind: "equipment",
        slot: "tool",
        bonus: { check: "survival", modifier: 1 },
    },
    {
        id: "dinosaur.bone-charm.v1",
        name: "Raptor Bone Charm",
        description: "Clicks softly when nearby predators change direction.",
        theme: "dinosaur",
        rarity: "rare",
        kind: "equipment",
        slot: "charm",
        bonus: { check: "perception", modifier: 1 },
    },
] as const;

const ITEM_BY_ID: ReadonlyMap<string, AdventureItemDefinition> = new Map(ADVENTURE_ITEMS.map(item => [item.id, item]));

export function getAdventureItem(id: string): AdventureItemDefinition | undefined {
    return ITEM_BY_ID.get(id);
}

export function getThemeLoot(theme: AdventureThemeCode): readonly AdventureItemDefinition[] {
    return ADVENTURE_ITEMS.filter(item => item.theme === theme);
}

export function selectThemeLoot(theme: AdventureThemeCode, adventureSeed: SeedPart, playerId: SeedPart): AdventureItemDefinition {
    const loot = getThemeLoot(theme);
    return pickWeightedSeeded(
        loot.map(item => ({ value: item, weight: LOOT_RARITY_WEIGHTS[item.rarity] })),
        "adventure-rpg-v1",
        adventureSeed,
        playerId,
        "loot",
        theme,
    );
}
