export const wrongPlaces = [
    "the neighbour's koi pond",
    "a restricted military zone",
    "the city fountain",
    "a private aquarium",
    "a wishing well",
    "the mall's decorative pond",
    "the general's swimming pool",
    "a children's inflatable pool",
    "a water treatment plant",
    "a historical landmark's moat",
    "a science lab's fish tank",
    "a theme park's water ride",
    "a hotel's luxury pool",
    "a zoo's penguin exhibit",
    "a public restroom's sink",
    "a baptismal font",
    "a bottle of mineral water",
    "a flooded basement",
    "a virtual aquarium screensaver",
    "a hot tub during a party",
    "a movie set ocean scene",
    "a haunted house bathtub",
    "the mayor's birdbath",
    "an indoor waterfall at a spa",
    "a pet store's turtle tank",
    "the fire department's water hose",
    "a neighbor's rain barrel",
    "the top of a water cooler",
    "a dehumidifier tray",
    "a fountain inside a casino",
];
export const fishingFriendlyQuestions = [
    "How are you doing today?",
    "How's your day going so far?",
    "What's new with you today?",
    "How are things on your end?",
    "Everything okay with you lately?",
    "How are you feeling today?",
    "How's life treating you right now?",
    "Got any good vibes going on today?",
    "What kind of mood are we in today?",
    "You doing alright over there?",
    "How's the weather in your world today?",
    "What's been the highlight of your day so far?",
    "Are you taking care of yourself?",
    "How's your energy level today?",
    "What's the vibe today?",
    "Got anything exciting going on?",
];

export const motivationalQuotes = [
    `You have to believe in yourself when no one else does. — Serena Williams`,
    `When you have a dream, you've got to grab it and never let go. — Carol Burnett`,
    `The most important thing is to enjoy your life— to be happy— it's all that matters. — Steve Jobs`,
    `Spread love everywhere you go. Let no one ever come without leaving happier. — Mother Teresa`,
    `Be yourself; everyone else is already taken. — Oscar Wilde`,
    `The biggest adventure you can take is to live the life of your dreams. — Oprah Winfrey`,
    `The only thing we have to fear is fear itself. — Franklin D. Roosevelt`,
    `Some people want it to happen, some wish it would happen, others make it happen. — Michael Jordan`,
    `You've got to be in it to win it. — Tony Robbins`,
    `It does not matter how slowly you go, as long as you do not stop. — Confucius`,
    `Find out who you are and do it on purpose. — Dolly Parton`,
    `For me, becoming isn't about arriving somewhere or achieving a certain aim. I see it instead as forward motion, a means of evolving, a way to reach continuously toward a better self. The journey doesn't end. — Michelle Obama`,
    `Confident people have a way of carrying themselves that makes others attracted to them. — Sofia Vergara`,
    `If you can do what you do best and be happy, you are further along in life than most people. — Leonardo DiCaprio`,
    `You can be everything. You can be the infinite amount of things that people are. — Kesha`,
    `Always go with your passions. Never ask yourself if it's realistic or not. — Deepak Chopra`,
    `When you change your thoughts, remember to also change your world. — Norman Vincent Peale`,
    `The more you know who you are, and what you want, the less you let things upset you. — Stephanie Perkins`,
    `By being yourself, you put something wonderful in the world that was not there before. — Edwin Elliot`,
    `Do one thing every day that scares you. — Eleanor Roosevelt`,
    `It is never too late to be what you might have been. — George Elliot`,
    `Find out who you are and be that person. That's what your soul was put on this earth to be. Find the truth, live that truth, and everything else will come. — Ellen DeGeneres`,
    `When we are no longer able to change a situation, we are challenged to change ourselves. — Viktor E. Frankl`,
    `If you cannot do great things, do small things in a great way. — Napoleon Hill`,
    `Always do your best. What you plant now, you will harvest later. — Og Mandino`,
    `Get busy living or get busy dying. — Stephen King`,
    `In three words I can sum up everything I've learned about life: It goes on. — Robert Frost`,
    `You can't help what you feel, but you can help how you behave. — Margaret Atwood`,
    `No need to hurry. No need to sparkle. No need to be anybody but oneself. — Virginia Woolf`,
    `Promise me you'll always remember: You're braver than you believe, and stronger than you seem, and smarter than you think. — A. A. Milne`,
    `Failure is a great teacher and, if you are open to it, every mistake has a lesson to offer. — Oprah Winfrey`,
    `If you don't like the road you're walking, start paving another one. — Dolly Parton`,
    `Don't let yesterday take up too much of today.— Will Rogers`,
    `Keep smiling, because life is a beautiful thing and there's so much to smile about. — Marilyn Monroe`,
    `Be persistent and never give up hope. — George Lucas`,
    `When we strive to become better than we are, everything around us becomes better too. — Paulo Coelho`,
    `Believe and act as if it were impossible to fail. — Charles Kettering`,
    `There are so many great things in life; why dwell on negativity? — Zendaya`,
    `Happiness often sneaks in through a door you didn't know you left open. — John Barrymore`,
    `Always remember that you are absolutely unique. Just like everyone else. — Margaret Mead`,
    `Keep your face towards the sunshine and shadows will fall behind you. — Walt Whitman`,
    `A problem is a chance for you to do your best. — Duke Ellington`,
    `You don't always need a plan. Sometimes you just need to breathe, trust, let go and see what happens. — Mandy Hale`,
    `Nothing is impossible. The word itself says 'I'm possible!' — Audrey Hepburn`,
    `Life does not have to be perfect to be wonderful. — Annette Funicello`,
    `It is during our darkest moments that we must focus to see the light. — Aristotle`,
    `The best way out is through. — Robert Frost`,
    `Don't be afraid to give up the good to go for the great. — John D. Rockefeller`,
    `Whether you think you can or you can't, you're right. — Henry Ford`,
    `Don't take yourself too seriously. Know when to laugh at yourself, and find a way to laugh at obstacles that inevitably present themselves. — Halle Bailey`,
    `Love the life you live. Live the life you love. — Bob Marley`,
    `Keep your face towards the sunshine and shadows will fall behind you. — Walt Whitman`,
    `The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson`,
    `I'm not going to continue knocking that old door that doesn't open for me. I'm going to create my own door and walk through that. — Ava DuVernay`,
    `If you change the way you look at things, the things you look at change. — Wayne Dyer`,
    `I believe that if you'll just stand up and go, life will open up for you. Something just motivates you to keep moving. — Tina Turner`,
    `Once you face your fear, nothing is ever as hard as you think. — Olivia Newton-John`,
    `Next time, ask 'What's the worst that will happen?' Then push yourself a little further than you dare. — Audre Lorde`,
    `Dreams do not come true just because you dream them. It's hard work that makes things happen. It's hard work that creates change. — Shonda Rhimes`,
    `Let us make our future now, and let us make our dreams tomorrow's reality. — Malala Yousafzai`,
    `You will face many defeats in life, but never let yourself be defeated. — Maya Angelou`,
    `The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt`,
    `Take the time to enjoy the little things, for one day you may look back and realize they were the big things. — Robert Brault`,
    `The future is not something we enter. The future is something we create. — Leonard I. Sweet`,
    `Life has got those twists and turns. You've got to hold on tight and off you go. — Nicole Kidman`,
    `The future belongs to those who prepare for it today. — Malcolm X`,
    `Don't wait around for other people to be happy for you. Any happiness you get you've got to make yourself. — Alice Walker`,
    `You miss 100% of the shots you don't take. — Wayne Gretzky`,
    `Life is a long lesson in humility. — James M. Barrie`,
    `You define your own life. Don't let other people write your script. — Oprah Winfrey`,
    `We must let go of the life we have planned, so as to accept the one that is waiting for us. — Joseph Campbell`,
    `We make a living by what we get, but we make a life by what we give. — Winston Churchill`,
    `Mistakes are a fact of life. It is the response to the error that counts. — Nikki Giovanni`,
    `When I let go of what I am, I become what I might be. — Lao Tzu`,
    `Ignore your mistakes. The number one thing to worry about is: Am I doing what I'm good at? — Max Levchin`,
    `If you are not willing to risk the usual, you will have to settle for the ordinary. — Jim Rohn`,
    `Life has no limitations, except the ones you make. — Les Brown`,
    `In the end, it's not the years in your life that count. It's life in your years. — Abraham Lincoln`,
    `You may not control all the events that happen to you, but you can decide not to be reduced by them. — Maya Angelou`,
    `Life is a succession of lessons which must be lived to be understood. — Ralph Waldo Emerson`,
    `Dreaming, after all, is a form of planning. — Gloria Steinem`,
    `We become what we think about most of the time. — Earl Nightingale`,
    `Life is very interesting…in the end, some of your greatest pains become your greatest strengths. — Drew Barrymore`,
    `Life is a daring adventure or it is nothing at all. — Helen Keller`,
    `All dreams are within reach. All you have to do is keep moving towards them. — Viola Davis`,
    `Life is made of ever so many partings welded together. — Charles Dickens`,
    `My interest is in the future because I am going to spend the rest of my life there. — Charles Kettering`,
    `Life is what happens to you when you are busy making other plans. — John Lennon`,
    `Yesterday is but today's memory and tomorrow is today's dream. — Khalil Gibran`,
    `It's amazing how a little tomorrow can make up for a whole lot of yesterday. — John Guare`,
    `Success is falling nine times and getting up 10. — Jon Bon Jovi`,
    `Start where you are. Use what you have. Do what you can. — Arthur Ashe`,
    `Success is stumbling from failure to failure with no loss of enthusiasm. — Winston Churchill`,
    `Before anything else, preparation is the key to success. — Alexander Graham Bell`,
    `Ambition is the path to success. Persistence is the vehicle you arrive in. — Bill Bradley`,
    `If you don't have any shadows you're not in the light. — Lady Gaga`,
    `There are no regrets in life. Just lessons. — Jennifer Aniston`,
    `Coming together is a beginning; keeping together is progress; working together is success. — Henry Ford`,
    `If you have knowledge, let others light their candles in it. — Margaret Fuller`,
    `A person who never made a mistake never tried anything new. — Albert Einstein`,
    `How dare you settle for less when the world made it so easy for you to be remarkable? — Seth Godin`,
    `Challenges are what make life interesting and overcoming them is what makes life meaningful. — Joshua J. Marine`,
    `We cannot solve problems with the kind of thinking we employed when we came up with them. — Albert Einstein`,
    `It's always better to shock people and change people's expectations than to give them exactly what they think you can do. — Jonah Hill`,
    `And when you want something, all the universe conspires in helping you achieve it. — Paulo Coelho`,
    `Don't judge each day by the harvest you reap but by the seeds that you plant. — Robert Louis Stevenson`,
    `It is better to fail in originality than to succeed in imitation. — Herman Melville`,
    `Don't worry about failure, you only have to be right once. — Drew Houston`,
    `Experience is a hard teacher because she gives the test first, the lesson afterwards. — Vernon Sanders Law`,
    `Dream big and dare to fail. — Norman Vaughan`,
    `Be sure you put your feet in the right place, then stand firm. — Abraham Lincoln`,
    `I'm not going to continue knocking on that old door that doesn't open for me. I'm going to create my own door and walk through that. — W.P. Kinsella`,
    `For the great doesn't happen through impulse alone, and is a succession of little things that are brought together. — Vincent Van Gogh`,
    `Life is a succession of lessons which must be lived to be understood. — Ralph Waldo Emerson`,
    `It's a good place when all you have is hope and not expectations. — Danny Boyle`,
    `Many of life's failures are people who did not realize how close they were to success when they gave up. — Thomas A. Edison`,
    `Never let the fear of striking out keep you from playing the game. — Babe Ruth`,
    `If you live long enough, you'll make mistakes. But if you learn from them, you'll be a better person. — Bill Clinton`,
    `To succeed in life, you need three things: a wishbone, a backbone, and a funnybone. — Reba McEntire`,
    `You have succeeded in life when all you really want is only what you really need. — Vernon Howard`,
    `Living might mean taking chances, but they're worth taking. — Lee Ann Womack`,
    `The simple things are also the most extraordinary things, and only the wise can see them. — Paulo Coelho`,
    `Live in the sunshine, swim the sea, drink the wild air. — Ralph Waldo Emerson`,
    `There is no perfection, only life. — Milan Kundera`,
    `I go to seek a Great Perhaps. — François Rabelais`,
    `My wish for you is that you continue. Continue to be who you are, to astonish a mean world with your acts of kindness. — Maya Angelou`,
    `The art of life is to know how to enjoy a little and to endure very much. — William Hazlitt`,
    `You only live once, but if you do it right, once is enough. — Mae West`,
    `There is no passion to be found playing small— in settling for a life that is less than the one you are capable of living. — Nelson Mandela`,
    `The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience. — Eleanor Roosevelt`,
    `The great courageous act that we must all do is to have the courage to step out of our history and past so that we can live our dreams. — Oprah Winfrey`,
    `Life isn't about finding yourself. Life is about creating yourself. — George Bernard Shaw`,
    `If you love life, don't waste time, for time is what life is made up of. — Bruce Lee`,
    `We are here to add what we can to life, not to get what we can from life. — William Osler`,
    `Be where you are; otherwise you will miss your life. —  Buddha`,
    `The purpose of life is a life of purpose. — Robert Byrne`,
    `We pass through this world but once. — Stephen Jay Gould`,
    `Life isn't a matter of milestones, but of moments. — Rose Kennedy`,
    `One of the deep secrets of life is that all that is really worth the doing is what we do for others. — Lewis Carroll`,
    `Life is tough my darling, but so are you. — Stephanie Bennett Henry`,
    `There's love enough in this world for everybody, if people will just look. — Kurt Vonnegut`,
    `Whatever we are, whatever we make of ourselves, is all we will ever have— and that, in its profound simplicity, is the meaning of life. — Philip Appleman`,
    `In the long run, the sharpest weapon of all is a kind and gentle spirit. — Anne Frank`,
    `Living an experience, a particular fate, is accepting it fully. — Albert Camus`,
    `So, what if, instead of thinking about solving your whole life, you just think about adding additional good things. One at a time. Just let your pile of good things grow. — Rainbow Rowell`,
    `Life isn't about waiting for the storm to pass, it's about learning to dance in the rain. — Vivian Greene`,
    `The new dawn blooms as we free it. For there is always light if only we're brave enough to see it, if only we're brave enough to be it. — Amanda Gorman`,
    `There is not one big cosmic meaning for all; there is only the meaning we each give to our life, an individual meaning, an individual plot, like an individual novel, a book for each person. — Anais Nin`,
    `The mystery of life isn't a problem to solve, but a reality to experience. — Frank Herbert`,
    `To love oneself is the beginning of a lifelong romance. — Oscar Wilde`,
];

export const friendlyCooldownMessages = [
    "Hope you're having a great day!",
    "Stay patient, the big one is coming!",
    "Hope you get a legendary next time!",
    "Remember to stay hydrated out there!",
    "Nice work! Take a breather, great catches need patience.",
    "Chill for a bit, the fish are just warming up for you.",
    "Good things come to those who wait, relax and enjoy the calm.",
    "Hold tight, your next big catch is on its way!",
    "Cooling down now, use this moment to get ready for the next cast.",
    "Patience pays off, take a moment to soak in the peaceful vibes.",
    "Rest your rod, the fish are gathering just for you.",
    "Keep calm and cool down, the waters will reward you soon.",
    "Pause, breathe, and get ready for your next winning cast.",
    "You're doing great! Sometimes the best catch comes after a little wait.",
];