name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: /root/adventures-node

      - name: Build and restart server service with Docker Compose
        run: |
          cd /root/adventures-node
          docker compose build server
          docker compose up -d server

      - name: Show running containers
        run: |
          cd /root/adventures-node
          docker ps
