name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Docker image
      #   run: |
      #     docker build -t ghcr.io/${{ github.repository }}:latest .

      # - name: Push Docker image
      #   run: |
      #     docker push ghcr.io/${{ github.repository }}:latest

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        env:
          REPO_PATH: ${{ vars.REPO_PATH }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: REPO_PATH
          script_path: scripts/deploy.sh
